<?php
require __DIR__ . '/../api/_bootstrap.php'; global $db;
$db->query("CREATE TABLE IF NOT EXISTS technologies (id INT PRIMARY KEY,branch VARCHAR(32) NOT NULL,tier INT NOT NULL,name VARCHAR(80) NOT NULL,description VARCHAR(255) NOT NULL,effect_key VARCHAR(40) NOT NULL,effect_value DECIMAL(8,2) NOT NULL DEFAULT 0,rp_cost INT NOT NULL,duration INT NOT NULL,center_level INT NOT NULL DEFAULT 1,prereq_id INT NULL,UNIQUE KEY branch_tier(branch,tier)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$db->query("CREATE TABLE IF NOT EXISTS research_state (userid INT UNSIGNED PRIMARY KEY,points DECIMAL(10,2) NOT NULL DEFAULT 30,last_tick INT NOT NULL,FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB");
$db->query("CREATE TABLE IF NOT EXISTS player_research (userid INT UNSIGNED NOT NULL,tech_id INT NOT NULL,completed_at INT NOT NULL,PRIMARY KEY(userid,tech_id),FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(tech_id) REFERENCES technologies(id)) ENGINE=InnoDB");
$db->query("CREATE TABLE IF NOT EXISTS research_jobs (userid INT UNSIGNED PRIMARY KEY,tech_id INT NOT NULL,due INT NOT NULL,FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(tech_id) REFERENCES technologies(id)) ENGINE=InnoDB");
$column=$db->query("SHOW COLUMNS FROM recipes LIKE 'unlock_tech'");if(!$column||!$column->num_rows)$db->query("ALTER TABLE recipes ADD unlock_tech INT NULL");
$techs=[
[101,'engineering',1,'Woodworking','Relearn reliable construction and field repairs.','unlock_repair',1,20,20,1,null],[102,'engineering',2,'Tool maintenance','Maintain tools and finish compound projects faster.','build_speed',10,35,35,1,101],[103,'engineering',3,'Iron working','Recover more useful metal from every salvage run.','salvage_bonus',15,60,55,2,102],[104,'engineering',4,'Steel working','Reinforce tools, structures and improvised weapons.','durability_bonus',25,90,80,3,103],
[201,'survival',1,'Food preservation','Reduce spoilage and improve food production.','food_rate',10,20,20,1,null],[202,'survival',2,'Pipeworks','Repair the compound water network.','water_rate',10,35,35,1,201],[203,'survival',3,'Greenhouse','Grow reliable food behind the compound walls.','food_rate',20,60,55,2,202],[204,'survival',4,'Water purification','Produce clean water from unsafe sources.','water_rate',25,90,80,3,203],
[301,'medicine',1,'Sterilization','Bandages heal more and infections are easier to control.','healing_bonus',1,20,20,1,null],[302,'medicine',2,'Wound treatment','Medical staff restore survivors faster.','recovery_rate',25,35,35,1,301],[303,'medicine',3,'Basic surgery','Improve treatment of serious combat wounds.','healing_bonus',2,60,55,2,302],[304,'medicine',4,'Antibiotics','Greatly accelerate recovery in the medical center.','recovery_rate',50,90,80,3,303],
[401,'combat',1,'Melee weapons','Unlock forging dependable machetes.','unlock_machete',1,20,20,1,null],[402,'combat',2,'Projectile weapons','Unlock improvised firearms.','unlock_pistol',1,35,35,1,401],[403,'combat',3,'Handguns','Unlock hand-loading 9mm ammunition.','unlock_ammo',1,60,55,2,402],[404,'combat',4,'Fire discipline','Train squads to make every attack count.','combat_bonus',2,90,80,3,403],
[501,'recon',1,'Lockpicking','Careful room entry finds more useful salvage.','room_loot',10,20,20,1,null],[502,'recon',2,'Reconnaissance','Plan routes and reduce expedition travel time.','travel_speed',15,35,35,1,501],[503,'recon',3,'Mapping','Reveal room threats with more starting intelligence.','intel_bonus',1,60,55,2,502],[504,'recon',4,'Signal triangulation','Coordinate expeditions through recovered radio signals.','travel_speed',25,90,80,3,503],
[601,'defense',1,'Barricades','Reinforce entrances before the nightly horde arrives.','defense_bonus',4,20,20,1,null],[602,'defense',2,'Barbed wire','Slow infected at the perimeter.','defense_bonus',6,35,35,1,601],[603,'defense',3,'Motion detectors','Give defenders warning before a breach.','defense_bonus',9,60,55,2,602],[604,'defense',4,'Automated guns','Turn recovered machinery into perimeter firepower.','defense_bonus',14,90,80,3,603],
[701,'energy',1,'Batteries','Store enough power to smooth out generator output.','power_bonus',2,20,20,1,null],[702,'energy',2,'Combustion engine','Improve fuel use and generator reliability.','petrol_rate',15,35,35,1,701],[703,'energy',3,'Power network','Distribute electricity efficiently across the compound.','power_bonus',4,60,55,2,702],[704,'energy',4,'Wind power','Supplement the generators with renewable power.','power_bonus',7,90,80,3,703]];
foreach($techs as$t){$branch=$db->real_escape_string($t[1]);$name=$db->real_escape_string($t[3]);$desc=$db->real_escape_string($t[4]);$effect=$db->real_escape_string($t[5]);$pre=$t[10]===null?'NULL':(string)(int)$t[10];$db->query("INSERT INTO technologies(id,branch,tier,name,description,effect_key,effect_value,rp_cost,duration,center_level,prereq_id) VALUES(".(int)$t[0].",'$branch',".(int)$t[2].",'$name','$desc','$effect',".(float)$t[6].",".(int)$t[7].",".(int)$t[8].",".(int)$t[9].",$pre) ON DUPLICATE KEY UPDATE branch=VALUES(branch),tier=VALUES(tier),name=VALUES(name),description=VALUES(description),effect_key=VALUES(effect_key),effect_value=VALUES(effect_value),rp_cost=VALUES(rp_cost),duration=VALUES(duration),center_level=VALUES(center_level),prereq_id=VALUES(prereq_id)");}
$db->query("INSERT IGNORE INTO research_state(userid,points,last_tick) SELECT userid,30,UNIX_TIMESTAMP() FROM strongholds");
$db->query("UPDATE recipes SET unlock_tech=CASE id WHEN 1 THEN 403 WHEN 2 THEN 402 WHEN 3 THEN 401 WHEN 5 THEN 101 ELSE NULL END");
echo "Research migration complete.\n";
