<?php
require_once __DIR__ . '/../api/_bootstrap.php';global $db;
$db->query("CREATE TABLE IF NOT EXISTS squads (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,userid INT UNSIGNED NOT NULL,name VARCHAR(40) NOT NULL,x INT NOT NULL,y INT NOT NULL,target_x INT NULL,target_y INT NULL,started_at INT NOT NULL DEFAULT 0,arrives_at INT NOT NULL DEFAULT 0,last_event VARCHAR(255) NOT NULL DEFAULT '',FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$db->query("CREATE TABLE IF NOT EXISTS squad_members (squad_id INT UNSIGNED NOT NULL,survivor_id INT UNSIGNED NOT NULL,PRIMARY KEY(squad_id,survivor_id),UNIQUE KEY one_squad_per_survivor(survivor_id),FOREIGN KEY(squad_id) REFERENCES squads(id) ON DELETE CASCADE,FOREIGN KEY(survivor_id) REFERENCES survivors(id) ON DELETE CASCADE) ENGINE=InnoDB");
$db->query("CREATE TABLE IF NOT EXISTS recruit_encounters (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,userid INT UNSIGNED NOT NULL,x INT NOT NULL,y INT NOT NULL,name VARCHAR(40) NOT NULL,attack_stat INT NOT NULL,defense_stat INT NOT NULL,found_at INT NOT NULL DEFAULT 0,joined_survivor INT UNSIGNED NULL,UNIQUE KEY user_recruit_tile(userid,x,y),FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(joined_survivor) REFERENCES survivors(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$db->query("CREATE TABLE IF NOT EXISTS training_jobs (survivor_id INT UNSIGNED PRIMARY KEY,userid INT UNSIGNED NOT NULL,focus VARCHAR(12) NOT NULL,due INT NOT NULL,started_at INT NOT NULL,FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(survivor_id) REFERENCES survivors(id) ON DELETE CASCADE) ENGINE=InnoDB");
$users=$db->query("SELECT userid,location FROM strongholds");while($users&&($u=$users->fetch_assoc())){$uid=(int)$u['userid'];[$hx,$hy]=array_map('intval',explode('|',$u['location']));$has=$db->query("SELECT id FROM squads WHERE userid=$uid LIMIT 1");if(!$has||!$has->num_rows){$legacy=$db->query("SELECT * FROM squad_travel WHERE userid=$uid LIMIT 1");if($legacy&&$legacy->num_rows){$s=$legacy->fetch_assoc();$tx=$s['target_x']===null?'NULL':(string)(int)$s['target_x'];$ty=$s['target_y']===null?'NULL':(string)(int)$s['target_y'];$db->query("INSERT INTO squads(userid,name,x,y,target_x,target_y,started_at,arrives_at) VALUES($uid,'Alpha',".(int)$s['x'].",".(int)$s['y'].",$tx,$ty,".(int)$s['started_at'].",".(int)$s['arrives_at'].")");$sid=(int)$db->insert_id;$crew=array_values(array_filter(array_map('intval',explode('|',(string)$s['crew']))));}else{$db->query("INSERT INTO squads(userid,name,x,y) VALUES($uid,'Alpha',$hx,$hy)");$sid=(int)$db->insert_id;$crew=[];}if(!$crew){$m=$db->query("SELECT id FROM survivors WHERE userid=$uid AND job_facility IS NULL ORDER BY id LIMIT 4");while($m&&($v=$m->fetch_assoc()))$crew[]=(int)$v['id'];}foreach($crew as$survivor)$db->query("INSERT IGNORE INTO squad_members(squad_id,survivor_id) VALUES($sid,$survivor)");}
 $count=$db->query("SELECT COUNT(*) n FROM recruit_encounters WHERE userid=$uid")->fetch_assoc();if((int)$count['n']===0){$names=zv2_npc_names($uid,8);$used=["$hx|$hy"=>true];for($i=0;$i<8;$i++){do{if($i<4){$x=max(1,min(50,$hx+random_int(-6,6)));$y=max(1,min(50,$hy+random_int(-6,6)));}else{$x=random_int(2,49);$y=random_int(2,49);}$key="$x|$y";}while(isset($used[$key]));$used[$key]=true;$name=$db->real_escape_string($names[$i]);$attack=2+(($uid+$i)%4);$defense=1+(($uid+$i*2)%3);$db->query("INSERT INTO recruit_encounters(userid,x,y,name,attack_stat,defense_stat) VALUES($uid,$x,$y,'$name',$attack,$defense)");}}
}
echo "Forces migration complete.\n";
