CREATE TABLE users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, username VARCHAR(20) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE strongholds (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, userid INT UNSIGNED NOT NULL UNIQUE,
  name VARCHAR(80) NOT NULL, level INT NOT NULL DEFAULT 1, points INT NOT NULL DEFAULT 0,
  location VARCHAR(7) NOT NULL, ressis VARCHAR(200) NOT NULL, rates VARCHAR(200) NOT NULL,
  population VARCHAR(200) NOT NULL, buildings VARCHAR(300) NOT NULL,
  activebuildings VARCHAR(300) NOT NULL, power VARCHAR(50) NOT NULL,
  last_tick INT NOT NULL, world_started INT NOT NULL, last_raid_cycle INT NOT NULL DEFAULT 0,
  FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE discovered (userid INT UNSIGNED PRIMARY KEY, data TEXT NOT NULL, FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE facilities (id INT PRIMARY KEY, name VARCHAR(80) NOT NULL, description VARCHAR(255) NOT NULL, maxlevel INT NOT NULL DEFAULT 10) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE facility_costs (facility_id INT NOT NULL, level INT NOT NULL, water INT DEFAULT 0, food INT DEFAULT 0, wood INT DEFAULT 0, metal INT DEFAULT 0, petrol INT DEFAULT 0, duration INT DEFAULT 30, PRIMARY KEY(facility_id,level)) ENGINE=InnoDB;
CREATE TABLE builds (userid INT UNSIGNED NOT NULL, slot INT NOT NULL, to_level INT NOT NULL, due INT NOT NULL, PRIMARY KEY(userid), FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE facility_positions (userid INT UNSIGNED NOT NULL,slot INT NOT NULL,grid_x INT NOT NULL,grid_y INT NOT NULL,PRIMARY KEY(userid,slot),UNIQUE KEY user_plot(userid,grid_x,grid_y),FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE technologies (id INT PRIMARY KEY,branch VARCHAR(32) NOT NULL,tier INT NOT NULL,name VARCHAR(80) NOT NULL,description VARCHAR(255) NOT NULL,effect_key VARCHAR(40) NOT NULL,effect_value DECIMAL(8,2) NOT NULL DEFAULT 0,rp_cost INT NOT NULL,duration INT NOT NULL,center_level INT NOT NULL DEFAULT 1,prereq_id INT NULL,UNIQUE KEY branch_tier(branch,tier)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE research_state (userid INT UNSIGNED PRIMARY KEY,points DECIMAL(10,2) NOT NULL DEFAULT 30,last_tick INT NOT NULL,FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE player_research (userid INT UNSIGNED NOT NULL,tech_id INT NOT NULL,completed_at INT NOT NULL,PRIMARY KEY(userid,tech_id),FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(tech_id) REFERENCES technologies(id)) ENGINE=InnoDB;
CREATE TABLE research_jobs (userid INT UNSIGNED PRIMARY KEY,tech_id INT NOT NULL,due INT NOT NULL,FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(tech_id) REFERENCES technologies(id)) ENGINE=InnoDB;
CREATE TABLE buildingtypes (id INT PRIMARY KEY, name VARCHAR(80) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE buildings (id INT AUTO_INCREMENT PRIMARY KEY, x INT NOT NULL, y INT NOT NULL, typ INT NOT NULL, count_rooms INT NOT NULL, buildingname VARCHAR(100) NOT NULL DEFAULT '', UNIQUE KEY world_xy(x,y)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE roomtypes (id INT PRIMARY KEY, name VARCHAR(80) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE items (id INT PRIMARY KEY, name VARCHAR(100) NOT NULL, category VARCHAR(40) NOT NULL, attack_bonus INT NOT NULL DEFAULT 0, healing INT NOT NULL DEFAULT 0, ammo_item INT NULL, max_durability INT NOT NULL DEFAULT 0, repair_amount INT NOT NULL DEFAULT 0, defense_bonus INT NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE zombietypes (id INT PRIMARY KEY, name VARCHAR(80) NOT NULL, threat INT NOT NULL DEFAULT 1) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE roommap (id INT AUTO_INCREMENT PRIMARY KEY, buildingid INT NOT NULL, type INT NOT NULL, inventory VARCHAR(500) NOT NULL DEFAULT '', zombies VARCHAR(500) NOT NULL DEFAULT '', FOREIGN KEY(buildingid) REFERENCES buildings(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE inventory (userid INT UNSIGNED NOT NULL, item_id INT NOT NULL, amount INT NOT NULL DEFAULT 0, durability INT NULL, PRIMARY KEY(userid,item_id), FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(item_id) REFERENCES items(id)) ENGINE=InnoDB;
CREATE TABLE survivors (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, userid INT UNSIGNED NOT NULL, name VARCHAR(40) NOT NULL, hp INT NOT NULL DEFAULT 12, max_hp INT NOT NULL DEFAULT 12, attack_stat INT NOT NULL DEFAULT 3, defense_stat INT NOT NULL DEFAULT 1, equipped_weapon INT NULL, job_facility INT NULL, fatigue DECIMAL(5,2) NOT NULL DEFAULT 0, recovery_progress DECIMAL(8,3) NOT NULL DEFAULT 0, FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(equipped_weapon) REFERENCES items(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE raids (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,userid INT UNSIGNED NOT NULL,day_number INT NOT NULL,threat INT NOT NULL,defense INT NOT NULL,success TINYINT(1) NOT NULL,resource_loss INT NOT NULL DEFAULT 0,wounded_survivor INT UNSIGNED NULL,damage INT NOT NULL DEFAULT 0,created_at INT NOT NULL,UNIQUE KEY user_day(userid,day_number),FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE room_progress (userid INT UNSIGNED NOT NULL,room_id INT NOT NULL,discovered TINYINT(1) NOT NULL DEFAULT 0,intel INT NOT NULL DEFAULT 0,approach VARCHAR(16) NOT NULL DEFAULT '',discovered_at INT NOT NULL DEFAULT 0,PRIMARY KEY(userid,room_id),FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(room_id) REFERENCES roommap(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE building_runs (userid INT UNSIGNED NOT NULL,building_id INT NOT NULL,momentum INT NOT NULL DEFAULT 0,reward_tier INT NOT NULL DEFAULT 0,noise INT NOT NULL DEFAULT 0,PRIMARY KEY(userid,building_id),FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(building_id) REFERENCES buildings(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE squads (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,userid INT UNSIGNED NOT NULL,name VARCHAR(40) NOT NULL,x INT NOT NULL,y INT NOT NULL,target_x INT NULL,target_y INT NULL,started_at INT NOT NULL DEFAULT 0,arrives_at INT NOT NULL DEFAULT 0,last_event VARCHAR(255) NOT NULL DEFAULT '',FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE squad_members (squad_id INT UNSIGNED NOT NULL,survivor_id INT UNSIGNED NOT NULL,PRIMARY KEY(squad_id,survivor_id),UNIQUE KEY one_squad_per_survivor(survivor_id),FOREIGN KEY(squad_id) REFERENCES squads(id) ON DELETE CASCADE,FOREIGN KEY(survivor_id) REFERENCES survivors(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE squad_equipment (squad_id INT UNSIGNED NOT NULL,item_id INT NOT NULL,amount INT NOT NULL DEFAULT 1,PRIMARY KEY(squad_id,item_id),FOREIGN KEY(squad_id) REFERENCES squads(id) ON DELETE CASCADE,FOREIGN KEY(item_id) REFERENCES items(id)) ENGINE=InnoDB;
CREATE TABLE hospital_treatments (survivor_id INT UNSIGNED PRIMARY KEY,userid INT UNSIGNED NOT NULL,started_at INT NOT NULL,due INT NOT NULL,soldier_level INT NOT NULL,hospital_level INT NOT NULL,FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(survivor_id) REFERENCES survivors(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE squad_cargo (squad_id INT UNSIGNED NOT NULL,item_id INT NOT NULL,amount INT NOT NULL DEFAULT 0,PRIMARY KEY(squad_id,item_id),FOREIGN KEY(squad_id) REFERENCES squads(id) ON DELETE CASCADE,FOREIGN KEY(item_id) REFERENCES items(id)) ENGINE=InnoDB;
CREATE TABLE squad_events (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,squad_id INT UNSIGNED NOT NULL,event_type VARCHAR(24) NOT NULL,message VARCHAR(255) NOT NULL,created_at INT NOT NULL,FOREIGN KEY(squad_id) REFERENCES squads(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE recruit_encounters (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,userid INT UNSIGNED NOT NULL,x INT NOT NULL,y INT NOT NULL,name VARCHAR(40) NOT NULL,attack_stat INT NOT NULL,defense_stat INT NOT NULL,found_at INT NOT NULL DEFAULT 0,joined_survivor INT UNSIGNED NULL,UNIQUE KEY user_recruit_tile(userid,x,y),FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(joined_survivor) REFERENCES survivors(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE training_jobs (survivor_id INT UNSIGNED PRIMARY KEY,userid INT UNSIGNED NOT NULL,focus VARCHAR(12) NOT NULL,due INT NOT NULL,started_at INT NOT NULL,FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(survivor_id) REFERENCES survivors(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE recipes (id INT PRIMARY KEY, name VARCHAR(100) NOT NULL, result_item INT NOT NULL, result_amount INT NOT NULL DEFAULT 1, unlock_tech INT NULL, toolshop_level INT NOT NULL DEFAULT 1, duration INT NOT NULL DEFAULT 10, category VARCHAR(32) NOT NULL DEFAULT 'tools', FOREIGN KEY(result_item) REFERENCES items(id), FOREIGN KEY(unlock_tech) REFERENCES technologies(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE recipe_ingredients (recipe_id INT NOT NULL, item_id INT NOT NULL, amount INT NOT NULL, PRIMARY KEY(recipe_id,item_id), FOREIGN KEY(recipe_id) REFERENCES recipes(id) ON DELETE CASCADE, FOREIGN KEY(item_id) REFERENCES items(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE production_jobs (userid INT UNSIGNED PRIMARY KEY,recipe_id INT NOT NULL,amount INT NOT NULL DEFAULT 1,due INT NOT NULL,started_at INT NOT NULL,FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(recipe_id) REFERENCES recipes(id)) ENGINE=InnoDB;

INSERT INTO facilities VALUES
(1,'Life support','Keeps water and air usable.',10),(2,'Scrapyard','Recovers wood and metal from ruins.',10),(3,'Garage','Maintains vehicles and produces fuel.',10),(4,'Storage','Protects scavenged supplies.',10),(8,'Fortifications','Walls, traps and firing positions.',10),(9,'Power generator','Produces electricity for the compound.',10),(10,'Troop quarters','Houses and equips defenders.',10),(11,'Toolshop','Builds weapons, tools, medicine and compound defenses.',10),(12,'Research center','Studies the infection and old technology.',10),(16,'Hospital','Treats critical squad casualties and restores them to duty.',10),(17,'Headquarters','Coordinates the survivor settlement.',10),(18,'Radio tower','Searches the wasteland for signals.',10);
INSERT INTO technologies VALUES
(101,'engineering',1,'Woodworking','Relearn reliable construction and field repairs.','unlock_repair',1,20,20,1,NULL),(102,'engineering',2,'Tool maintenance','Maintain tools and finish compound projects faster.','build_speed',10,35,35,1,101),(103,'engineering',3,'Iron working','Recover more useful metal from every salvage run.','salvage_bonus',15,60,55,2,102),(104,'engineering',4,'Steel working','Reinforce tools, structures and improvised weapons.','durability_bonus',25,90,80,3,103),
(201,'survival',1,'Food preservation','Reduce spoilage and improve food production.','food_rate',10,20,20,1,NULL),(202,'survival',2,'Pipeworks','Repair the compound water network.','water_rate',10,35,35,1,201),(203,'survival',3,'Greenhouse','Grow reliable food behind the compound walls.','food_rate',20,60,55,2,202),(204,'survival',4,'Water purification','Produce clean water from unsafe sources.','water_rate',25,90,80,3,203),
(301,'medicine',1,'Sterilization','Bandages heal more and infections are easier to control.','healing_bonus',1,20,20,1,NULL),(302,'medicine',2,'Wound treatment','Medical staff restore survivors faster.','recovery_rate',25,35,35,1,301),(303,'medicine',3,'Basic surgery','Improve treatment of serious combat wounds.','healing_bonus',2,60,55,2,302),(304,'medicine',4,'Antibiotics','Greatly accelerate recovery in the medical center.','recovery_rate',50,90,80,3,303),
(401,'combat',1,'Melee weapons','Unlock forging dependable machetes.','unlock_machete',1,20,20,1,NULL),(402,'combat',2,'Projectile weapons','Unlock improvised firearms.','unlock_pistol',1,35,35,1,401),(403,'combat',3,'Handguns','Unlock hand-loading 9mm ammunition.','unlock_ammo',1,60,55,2,402),(404,'combat',4,'Fire discipline','Train squads to make every attack count.','combat_bonus',2,90,80,3,403),
(501,'recon',1,'Lockpicking','Careful room entry finds more useful salvage.','room_loot',10,20,20,1,NULL),(502,'recon',2,'Reconnaissance','Plan routes and reduce expedition travel time.','travel_speed',15,35,35,1,501),(503,'recon',3,'Mapping','Reveal room threats with more starting intelligence.','intel_bonus',1,60,55,2,502),(504,'recon',4,'Signal triangulation','Coordinate expeditions through recovered radio signals.','travel_speed',25,90,80,3,503),
(601,'defense',1,'Barricades','Reinforce entrances before the nightly horde arrives.','defense_bonus',4,20,20,1,NULL),(602,'defense',2,'Barbed wire','Slow infected at the perimeter.','defense_bonus',6,35,35,1,601),(603,'defense',3,'Motion detectors','Give defenders warning before a breach.','defense_bonus',9,60,55,2,602),(604,'defense',4,'Automated guns','Turn recovered machinery into perimeter firepower.','defense_bonus',14,90,80,3,603),
(701,'energy',1,'Batteries','Store enough power to smooth out generator output.','power_bonus',2,20,20,1,NULL),(702,'energy',2,'Combustion engine','Improve fuel use and generator reliability.','petrol_rate',15,35,35,1,701),(703,'energy',3,'Power network','Distribute electricity efficiently across the compound.','power_bonus',4,60,55,2,702),(704,'energy',4,'Wind power','Supplement the generators with renewable power.','power_bonus',7,90,80,3,703);
INSERT INTO buildingtypes VALUES (1,'Residential house'),(2,'Office tower'),(3,'Pharmacy'),(4,'Gun shop'),(5,'Warehouse'),(6,'Hospital'),(7,'Supermarket'),(8,'Police station'),(9,'Factory'),(10,'Bar');
INSERT INTO roomtypes VALUES (1,'Entrance'),(2,'Hallway'),(3,'Living room'),(4,'Storage'),(5,'Kitchen'),(6,'Office'),(7,'Treatment room'),(8,'Workshop'),(9,'Cellar');
INSERT INTO items VALUES (1,'Scrap metal','material',0,0,NULL,0,0,0),(2,'Timber','material',0,0,NULL,0,0,0),(3,'Canned food','food',0,1,NULL,0,0,0),(4,'Clean water','drink',0,1,NULL,0,0,0),(5,'Bandages','medicine',0,5,NULL,0,0,0),(6,'9mm ammunition','ammo',0,0,NULL,0,0,0),(7,'Fuel can','fuel',0,0,NULL,0,0,0),(8,'Old-world electronics','technology',0,0,NULL,0,0,0),(9,'Pipe pistol','weapon',3,0,6,12,0,0),(10,'Machete','weapon',2,0,NULL,18,0,0),(11,'Repair kit','repair',0,0,NULL,0,8,0),(12,'Wooden club','weapon',2,0,NULL,16,0,0),(13,'Crowbar','weapon',3,0,NULL,24,0,0),(14,'Fire axe','weapon',4,0,NULL,28,0,0),(15,'Reinforced machete','weapon',5,0,NULL,35,0,0),(16,'Zip gun','weapon',4,0,6,10,0,0),(17,'Service pistol','weapon',5,0,6,22,0,0),(18,'Shotgun shells','ammo',0,0,NULL,0,0,0),(19,'Pump shotgun','weapon',7,0,18,25,0,0),(20,'Field medkit','medicine',0,9,NULL,0,0,0),(21,'Advanced repair kit','repair',0,0,NULL,0,14,0),(22,'Window barricade','fortification',0,0,NULL,0,0,2),(23,'Barbed barricade','fortification',0,0,NULL,0,0,4),(24,'Motion alarm','fortification',0,0,NULL,0,0,6),(25,'Auto-turret','fortification',0,0,6,30,0,10),(26,'Lockpick set','equipment',0,0,NULL,20,0,0);
INSERT INTO recipes VALUES (1,'Hand-load 9mm rounds',6,6,403,2,12,'ammunition'),(2,'Build pipe pistol',9,1,402,2,22,'firearms'),(3,'Forge machete',10,1,401,1,14,'melee'),(4,'Make bandages',5,2,301,1,10,'medical'),(5,'Assemble repair kit',11,1,101,1,12,'tools'),(6,'Carve wooden club',12,1,NULL,1,8,'melee'),(7,'Forge crowbar',13,1,101,1,12,'tools'),(8,'Forge fire axe',14,1,103,3,24,'melee'),(9,'Reinforce machete',15,1,404,4,32,'melee'),(10,'Build zip gun',16,1,402,2,20,'firearms'),(11,'Restore service pistol',17,1,403,3,30,'firearms'),(12,'Load shotgun shells',18,4,403,3,16,'ammunition'),(13,'Build pump shotgun',19,1,404,4,40,'firearms'),(14,'Pack field medkit',20,1,301,2,18,'medical'),(15,'Assemble advanced repair kit',21,1,102,2,20,'tools'),(16,'Build window barricade',22,1,601,1,12,'defenses'),(17,'Build barbed barricade',23,1,602,2,20,'defenses'),(18,'Assemble motion alarm',24,1,603,3,28,'defenses'),(19,'Assemble auto-turret',25,1,604,4,45,'defenses'),(20,'Make lockpick set',26,1,501,2,16,'tools');
INSERT INTO recipe_ingredients VALUES (1,1,2),(2,1,4),(2,8,2),(3,1,3),(3,2,1),(4,2,1),(4,4,1),(5,1,2),(5,2,1),(6,2,2),(7,1,3),(8,1,5),(8,2,2),(9,1,7),(9,10,1),(10,1,5),(10,8,1),(11,1,8),(11,8,2),(12,1,3),(13,1,12),(13,8,3),(14,2,2),(14,4,2),(14,5,1),(15,1,4),(15,8,1),(16,2,5),(16,1,2),(17,2,4),(17,1,5),(18,1,6),(18,8,2),(19,1,15),(19,8,6),(19,6,6),(20,1,2),(20,8,1);
INSERT INTO zombietypes VALUES (1,'Shambler',1),(2,'Runner',2),(3,'Bloated infected',3);
