import { makeDraggable } from './draggable.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createForces(el,opts={}){
 const dragger=makeDraggable(el,{handle:'.forces-card header',target:'.forces-card',storageKey:'zv2.window.forces'});
 let data=null;const act=opts.onAction||(()=>{}),select=opts.onSelect||(()=>{}),equipment=opts.onEquipment||(()=>{});
 el.addEventListener('click',e=>{if(e.target.closest('[data-forces-close]'))return hide();if(e.target.closest('[data-open-equipment]'))return equipment();const b=e.target.closest('[data-force-action]');if(b&&!b.disabled){b.disabled=true;act(b.dataset.forceAction,Number(b.dataset.survivor||0),Number(b.dataset.squad||0),b.dataset.focus||'');}const s=e.target.closest('[data-select-squad]');if(s){select(Number(s.dataset.selectSquad));show(data);}});
 function hide(){el.classList.remove('open');el.innerHTML='';}function isOpen(){return el.classList.contains('open');}
 function show(d,active=0){data=d;const bySquad=new Map((d.squads||[]).map(s=>[s.id,(d.survivors||[]).filter(v=>v.squadId===s.id)]));const home=d.home||{};
  const squads=(d.squads||[]).map(s=>{const members=bySquad.get(s.id)||[],atHome=!s.traveling&&s.x===home.x&&s.y===home.y,cargo=s.cargo||{items:[],used:0,capacity:members.length*8},ready=members.filter(v=>v.hp>0&&v.fatigue<90&&!v.job).length;return `<article class="force-squad ${s.id===active?'selected':''}"><div class="force-squad-title"><div><b>${esc(s.name)}</b><small>${s.traveling?`en route to ${s.targetX}|${s.targetY}`:`at ${s.x}|${s.y}`} · ${ready}/${members.length} ready</small></div><div class="force-command-buttons"><button data-select-squad="${s.id}">${s.id===active?'Selected':'Deploy'}</button><button class="return-home" data-force-action="return" data-squad="${s.id}"${atHome||s.traveling||!members.length?' disabled':''}>${atHome?'At home':s.traveling?'Traveling…':'Return home'}</button></div></div><div class="force-readiness"><span>Cargo ${cargo.used}/${cargo.capacity} kg</span><i><em style="width:${cargo.capacity?Math.min(100,cargo.used/cargo.capacity*100):0}%"></em></i><small>${cargo.items.length?cargo.items.map(i=>`${esc(i.name)} ×${i.amount}`).join(' · '):'Empty'}${!d.storage?.acceptsLoot?' · Build Storage to deposit loot on return':''}</small></div>${members.length?members.map(v=>`<div class="force-person"><span><b>${esc(v.name)}</b><small>ATK ${v.attack} · DEF ${v.defense} · ${esc(v.weapon||'unarmed')}</small></span><button data-force-action="remove" data-survivor="${v.id}" data-squad="${s.id}"${atHome?'':' disabled'}>Reserve</button></div>`).join(''):'<p class="force-empty">No one assigned.</p>'}</article>`}).join('');
  const reserve=(d.survivors||[]).filter(v=>!v.squadId);const reserveRows=reserve.map(v=>`<article class="reserve-person"><div><b>${esc(v.name)}</b><small>ATK ${v.attack} · DEF ${v.defense} · ${esc(v.weapon||'unarmed')}${v.job?' · facility duty':''}</small>${v.training?`<em>${esc(v.training.focus)} training · <span data-training-due="${v.training.due}"></span></em>`:''}</div><div class="reserve-actions">${(d.squads||[]).map(s=>`<button data-force-action="assign" data-survivor="${v.id}" data-squad="${s.id}"${v.job||v.training||s.traveling||s.x!==home.x||s.y!==home.y?' disabled':''}>Join ${esc(s.name)}</button>`).join('')}${d.quarters.level?`<button data-force-action="train" data-survivor="${v.id}" data-focus="attack"${v.job||v.training?' disabled':''}>Train ATK</button><button data-force-action="train" data-survivor="${v.id}" data-focus="defense"${v.job||v.training?' disabled':''}>Train DEF</button>`:''}</div></article>`).join('')||'<p class="force-empty">No survivors in reserve.</p>';
  el.innerHTML=`<div class="forces-card"><header title="Drag to move"><div><small>SURVIVOR COMMAND</small><h2>Squads & Troop Quarters</h2></div><button data-forces-close>✕</button></header><div class="forces-summary"><span>Troop Quarters <b>Level ${d.quarters.level}</b></span><span>Squads <b>${d.squads.length}/${d.quarters.squadLimit}</b></span><span>Training slots <b>${(d.survivors||[]).filter(v=>v.training).length}/${d.quarters.trainingCapacity}</b></span><span>Recruits found <b>${d.recruits.found}/${d.recruits.total}</b></span></div>${d.quarters.level?'<p class="recruit-intel">Named survivors are hiding throughout unexplored city blocks. Reach their location and they will join your reserve.</p>':'<p class="forces-warning">Build Troop Quarters to form more squads and train reserve survivors.</p>'}<div class="forces-body"><section><div class="forces-heading"><h3>Active squads</h3><button data-force-action="create"${d.squads.length>=d.quarters.squadLimit?' disabled':''}>+ Form squad</button></div>${squads}</section><section><h3>Stronghold reserve</h3>${reserveRows}</section></div></div>`;el.classList.add('open');dragger.restore();tick();
 }
 function tick(){el.querySelectorAll('[data-training-due]').forEach(n=>{const s=Math.max(0,Number(n.dataset.trainingDue)-Math.floor(Date.now()/1000));n.textContent=s?`${s}s remaining`:'finishing…';});}
 setInterval(tick,1000);return{show,hide,isOpen};
}
