import { makeDraggable } from './draggable.js';
const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={ammunition:'Ammunition',defenses:'Compound defenses',firearms:'Firearms',medical:'Medical supplies',melee:'Melee weapons',tools:'Tools & equipment'};
export function createToolshop(el,opts={}){
 const onProduce=opts.onProduce||(()=>{});const dragger=makeDraggable(el,{handle:'.toolshop-card header',target:'.toolshop-card',storageKey:'zv2.window.toolshop'});
 el.addEventListener('click',e=>{if(e.target.closest('[data-toolshop-close]')){hide();return;}const b=e.target.closest('[data-produce]');if(b&&!b.disabled){b.disabled=true;onProduce(Number(b.dataset.produce));}});
 function hide(){el.classList.remove('open');el.innerHTML='';}function isOpen(){return el.classList.contains('open');}
 function show(data){const shop=data.toolshop||{level:0,technicians:0,job:null};const groups={};for(const r of data.recipes||[])(groups[r.category]??=[]).push(r);const sections=Object.entries(groups).map(([cat,recipes])=>`<section class="production-group"><h3>${esc(labels[cat]||cat)}</h3><div class="production-list">${recipes.map(r=>`<article class="production-item ${r.canCraft?'ready':'locked'}"><div class="production-level">TOOLSHOP L${r.toolshopLevel} · ${r.techniciansRequired} TECH</div><b>${esc(r.result.amount+'× '+r.result.name)}</b><small>${esc(r.name)} · ${r.duration}s base time</small><ul>${r.ingredients.map(i=>`<li class="${i.owned<i.amount?'missing':''}">${esc(i.name)} <span>${i.owned}/${i.amount}</span></li>`).join('')}</ul><div class="production-tech">${r.requiredTech?'Research: '+esc(r.requiredTech):'Basic workshop design'}</div><button data-produce="${r.id}"${r.canCraft?'':' disabled'}>${r.canCraft?'Produce':esc(r.reason||'Unavailable')}</button></article>`).join('')}</div></section>`).join('');const job=shop.job?`<div class="production-job"><div><small>PRODUCTION ACTIVE</small><b>${esc(shop.job.name)} → ${esc(shop.job.result)}</b></div><span data-production-countdown data-due="${shop.job.due}"></span></div>`:'';const staffing=shop.level?`<div class="toolshop-warning">${shop.technicians} rested technician${shop.technicians===1?'':'s'} assigned · at least one is required</div>`:'';el.innerHTML=`<div class="toolshop-card"><header title="Drag to move"><div><small>COMPOUND MANUFACTURING</small><h2>Toolshop · Level ${shop.level}</h2></div><button data-toolshop-close aria-label="Close">✕</button></header>${shop.level?job:'<div class="toolshop-warning">Construct and place the Toolshop before producing equipment.</div>'}${staffing}<div class="production-catalog">${sections}</div></div>`;el.classList.add('open');dragger.restore();tick();}
 function tick(){const c=el.querySelector('[data-production-countdown]');if(!c)return;const seconds=Math.max(0,Number(c.dataset.due)-Math.floor(Date.now()/1000));c.textContent=seconds?`${seconds}s remaining`:'finishing…';}
 setInterval(tick,1000);return{show,hide,isOpen};
}
