<?php
require __DIR__ . '/_bootstrap.php';global $db;$uid=api_require_user();$squadId=(int)($_GET['squad']??0);
$x=(int)($_GET['x']??0);$y=(int)($_GET['y']??0);if($x<1||$x>50||$y<1||$y>50)json_err('bad_tile','That is off the map.');if(!zv2_is_seen($uid,$x,$y))json_err('not_discovered','Explore this place before entering it.',403);
$squad=zv2_squad($uid,$squadId);if($squad['traveling'])json_err('squad_traveling','The squad has not arrived yet.');if($squad['x']!==$x||$squad['y']!==$y)json_err('squad_elsewhere','Move the selected squad to this location first.');$crew=$squad['crew'];if(!$crew)json_err('no_crew','No raiding crew is present.');$crewSql=implode(',',array_map('intval',$crew));$gear=$squad['equipment'];$gearAttack=(int)$gear['perMemberAttack'];$gearDefense=(int)$gear['perMemberDefense'];
$br=$db->query("SELECT b.id,b.typ,b.buildingname,t.name typename FROM buildings b LEFT JOIN buildingtypes t ON t.id=b.typ WHERE b.x=$x AND b.y=$y LIMIT 1");if(!$br||!$br->num_rows)json_err('no_building','There is no building here.',404);$building=$br->fetch_assoc();$bid=(int)$building['id'];
$home=$db->query("SELECT location FROM strongholds WHERE userid=$uid LIMIT 1");if($home&&$home->num_rows&&$home->fetch_assoc()['location']==="$x|$y")json_err('is_home','This is your stronghold, not a ruin.');
$name=trim((string)$building['buildingname']);if($name==='')$name=(string)($building['typename']??'Ruins');
$db->query("INSERT IGNORE INTO building_runs(userid,building_id) VALUES($uid,$bid)");$first=$db->query("SELECT id FROM roommap WHERE buildingid=$bid ORDER BY id LIMIT 1");if($first&&$first->num_rows){$fid=(int)$first->fetch_assoc()['id'];$db->query("INSERT INTO room_progress(userid,room_id,discovered,intel,approach,discovered_at) VALUES($uid,$fid,1,1,'entry',".time().") ON DUPLICATE KEY UPDATE discovered=GREATEST(discovered,1)");}
$progress=[];$pr=$db->query("SELECT room_id,discovered,intel,approach FROM room_progress WHERE userid=$uid");while($pr&&($p=$pr->fetch_assoc()))$progress[(int)$p['room_id']]=$p;
$raw=[];$rr=$db->query("SELECT r.id,r.type,r.inventory,r.zombies,rt.name FROM roommap r LEFT JOIN roomtypes rt ON rt.id=r.type WHERE r.buildingid=$bid ORDER BY r.id");while($rr&&($row=$rr->fetch_assoc()))$raw[]=$row;
$rooms=[];$chainOpen=true;foreach($raw as$i=>$row){$rid=(int)$row['id'];$p=$progress[$rid]??null;$discovered=(bool)($p&&$p['discovered']);$accessible=!$discovered&&$chainOpen;$items=[];$infected=[];$zombieCount=0;
 if($discovered){foreach(explode('&',(string)$row['inventory'])as$entry){if($entry==='')continue;$bits=explode('|',$entry);$iid=(int)($bits[0]??0);$amount=max(0,(int)($bits[1]??0));if($iid&&$amount)$items[]=['id'=>$iid,'name'=>zv2_item_name($iid),'amount'=>$amount,'owned'=>zv2_item_owned($uid,$iid)];}foreach(explode('&',(string)$row['zombies'])as$entry){if($entry==='')continue;$bits=explode('|',$entry);$zid=(int)($bits[0]??0);$amount=max(0,(int)($bits[1]??0));if(!$zid||!$amount)continue;$zr=$db->query("SELECT name,threat,hp,attack,defense FROM zombietypes WHERE id=$zid LIMIT 1");$zd=$zr&&$zr->num_rows?$zr->fetch_assoc():['name'=>'Zombie','threat'=>1,'hp'=>10,'attack'=>5,'defense'=>5];$frontHp=isset($bits[2])?max(1,(int)$bits[2]):(int)$zd['hp'];$infected[]=['type'=>$zid,'name'=>$zd['name'],'amount'=>$amount,'threat'=>(int)$zd['threat'],'hp'=>(int)$zd['hp'],'attack'=>(int)$zd['attack'],'defense'=>(int)$zd['defense'],'frontHp'=>$frontHp];$zombieCount+=$amount;}}
 $vehicles=[];if($discovered){$wv=$db->query("SELECT wv.id,wv.name,wv.fuel,vt.seats,vt.cargo_bonus,vt.speed_bonus,vt.fuel_capacity FROM world_vehicles wv JOIN vehicle_types vt ON vt.id=wv.type_id WHERE wv.room_id=$rid AND wv.claimed_by IS NULL");while($wv&&($v=$wv->fetch_assoc()))$vehicles[]=['id'=>(int)$v['id'],'name'=>$v['name'],'fuel'=>(int)$v['fuel'],'fuelCapacity'=>(int)$v['fuel_capacity'],'seats'=>(int)$v['seats'],'cargoBonus'=>(int)$v['cargo_bonus'],'speedBonus'=>(int)$v['speed_bonus']];}
 $rooms[]=['id'=>$rid,'index'=>$i+1,'gridX'=>$i%3,'gridY'=>(int)floor($i/3),'discovered'=>$discovered,'accessible'=>$accessible,'name'=>$discovered?(string)($row['name']??'Room'):'Unknown room','loot'=>$discovered?array_sum(array_column($items,'amount')):null,'items'=>$items,'zombies'=>$discovered?$zombieCount:null,'infected'=>$infected,'vehicles'=>$vehicles,'intel'=>$discovered?(int)($p['intel']??0):0,'approach'=>$discovered?(string)($p['approach']??''):''];
 if(!$discovered||$zombieCount>0)$chainOpen=false;
}
$clearance=zv2_mark_building_cleared($uid,$bid);$run=$db->query("SELECT momentum,reward_tier,noise,cleared_at FROM building_runs WHERE userid=$uid AND building_id=$bid")->fetch_assoc();
$survivors=[];$sq=$db->query("SELECT s.id,s.name,s.hp,s.max_hp,s.attack_stat,s.defense_stat,s.job_facility,s.fatigue,f.name job_name,i.name weapon,i.attack_bonus,i.ammo_item,i.max_durability,COALESCE(v.durability,i.max_durability) durability,COALESCE(a.amount,0) ammo FROM survivors s LEFT JOIN facilities f ON f.id=s.job_facility LEFT JOIN items i ON i.id=s.equipped_weapon LEFT JOIN inventory v ON v.userid=s.userid AND v.item_id=s.equipped_weapon LEFT JOIN inventory a ON a.userid=s.userid AND a.item_id=i.ammo_item WHERE s.userid=$uid AND s.id IN($crewSql) AND s.job_facility IS NULL ORDER BY s.id");
while($sq&&($s=$sq->fetch_assoc())){$ready=(int)($s['durability']??0)>0&&((int)($s['ammo_item']??0)===0||(int)$s['ammo']>0);$available=(int)$s['hp']>0&&(float)$s['fatigue']<90&&$s['job_facility']===null;$reason=(int)$s['hp']<=0?'downed':((float)$s['fatigue']>=90?'exhausted':($s['job_facility']!==null?'working at '.$s['job_name']:null));$survivors[]=['id'=>(int)$s['id'],'name'=>$s['name'],'hp'=>(int)$s['hp'],'maxHp'=>(int)$s['max_hp'],'attack'=>(int)$s['attack_stat']+($ready?(int)$s['attack_bonus']:0)+$gearAttack,'defense'=>(int)$s['defense_stat']+$gearDefense,'weapon'=>$s['weapon'],'gearAttack'=>$gearAttack,'gearDefense'=>$gearDefense,'ammoItem'=>$s['ammo_item']===null?null:(int)$s['ammo_item'],'ammo'=>(int)$s['ammo'],'durability'=>$s['durability']===null?null:(int)$s['durability'],'maxDurability'=>(int)($s['max_durability']??0),'fatigue'=>round((float)$s['fatigue']),'available'=>$available,'unavailableReason'=>$reason];}
json_out(['ok'=>true,'run'=>['momentum'=>(int)$run['momentum'],'rewardTier'=>(int)$run['reward_tier'],'nextReward'=>((int)$run['reward_tier']+1)*5,'noise'=>(int)$run['noise']],'cargo'=>zv2_squad_cargo($squad['id']),'squadEquipment'=>$gear,'survivors'=>$survivors,'building'=>['id'=>$bid,'x'=>$x,'y'=>$y,'type'=>(int)$building['typ'],'name'=>$name,'rooms'=>$rooms,'cleared'=>(int)$run['cleared_at']>0,'clearance'=>$clearance]]);
