<?php
require __DIR__ . '/_bootstrap.php';global $db;$uid=api_require_user();
if(($_SERVER['REQUEST_METHOD']??'GET')!=='POST')json_err('method','POST required',405);zv2_refresh($uid);
$recipeId=(int)($_POST['recipe']??0);if($recipeId<=0)json_err('bad_recipe','Choose a recipe.');
$rr=$db->query("SELECT r.*,i.name result_name FROM recipes r JOIN items i ON i.id=r.result_item WHERE r.id=$recipeId LIMIT 1");if(!$rr||!$rr->num_rows)json_err('bad_recipe','That recipe does not exist.');$recipe=$rr->fetch_assoc();
$hold=$db->query("SELECT buildings FROM strongholds WHERE userid=$uid LIMIT 1")->fetch_assoc();$levels=pipe_nums($hold['buildings']);$shop=(int)($levels[11]??0);if($shop<=0)json_err('no_toolshop','Construct a Toolshop first.');if($shop<(int)$recipe['toolshop_level'])json_err('toolshop_level','Toolshop level '.(int)$recipe['toolshop_level'].' required.');if($recipe['unlock_tech']!==null&&!zv2_has_tech($uid,(int)$recipe['unlock_tech']))json_err('recipe_locked','Recover the required technology first.');$workers=$db->query("SELECT COUNT(*) n FROM survivors WHERE userid=$uid AND job_facility=11 AND hp>0 AND fatigue<90")->fetch_assoc();$technicians=(int)$workers['n'];if($technicians<(int)$recipe['technicians_required'])json_err('technicians_required','Assign at least '.(int)$recipe['technicians_required'].' rested technician(s) to the Toolshop.');
$busy=$db->query("SELECT 1 FROM production_jobs WHERE userid=$uid LIMIT 1");if($busy&&$busy->num_rows)json_err('production_busy','The Toolshop is already producing an item.');
$ingredients=[];$ir=$db->query("SELECT ri.item_id,ri.amount,i.name FROM recipe_ingredients ri JOIN items i ON i.id=ri.item_id WHERE ri.recipe_id=$recipeId");while($ir&&($row=$ir->fetch_assoc()))$ingredients[]=['id'=>(int)$row['item_id'],'amount'=>(int)$row['amount'],'name'=>$row['name']];
$speed=1+max(0,$shop-1)*.05+$technicians*.15;$duration=max(4,(int)ceil((int)$recipe['duration']/$speed));$started=time();$due=$started+$duration;
$db->begin_transaction();try{foreach($ingredients as$ingredient){$owned=$db->query("SELECT amount FROM inventory WHERE userid=$uid AND item_id={$ingredient['id']} FOR UPDATE");if(!$owned||!$owned->num_rows||(int)$owned->fetch_assoc()['amount']<$ingredient['amount'])throw new RuntimeException('materials');}foreach($ingredients as$ingredient)$db->query("UPDATE inventory SET amount=amount-{$ingredient['amount']} WHERE userid=$uid AND item_id={$ingredient['id']}");$db->query("DELETE FROM inventory WHERE userid=$uid AND amount<=0");$db->query("INSERT INTO production_jobs(userid,recipe_id,amount,due,started_at) VALUES($uid,$recipeId,1,$due,$started)");$db->commit();}catch(RuntimeException$e){$db->rollback();json_err('materials','You do not have the required materials.');}catch(Throwable$e){$db->rollback();throw$e;}
json_out(['ok'=>true,'job'=>['recipeId'=>$recipeId,'name'=>$recipe['name'],'result'=>$recipe['result_name'],'startedAt'=>$started,'due'=>$due,'seconds'=>$duration],'message'=>$recipe['name'].' entered production.']);
