<?php
require __DIR__ . '/_bootstrap.php';global $db;$uid=api_require_user();if(($_SERVER['REQUEST_METHOD']??'GET')!=='POST')json_err('method','POST required',405);
$slot=(int)($_POST['slot']??0);$survivor=(int)($_POST['survivor']??0);$action=(string)($_POST['action']??'assign');if($slot<1||$survivor<=0)json_err('bad_assignment','Choose a facility and survivor.');zv2_refresh($uid);
$hr=$db->query("SELECT buildings FROM strongholds WHERE userid=$uid LIMIT 1");if(!$hr||!$hr->num_rows)json_err('no_stronghold','Stronghold not found.',404);$levels=pipe_nums($hr->fetch_assoc()['buildings']);$level=(int)($levels[$slot]??0);if($level<=0)json_err('not_built','That facility has not been built.');
$sr=$db->query("SELECT name,hp,fatigue,job_facility FROM survivors WHERE id=$survivor AND userid=$uid LIMIT 1");if(!$sr||!$sr->num_rows)json_err('bad_survivor','Choose one of your survivors.');$sv=$sr->fetch_assoc();
if($action==='unassign'){$db->query("UPDATE survivors SET job_facility=NULL WHERE id=$survivor AND userid=$uid");json_out(['ok'=>true,'message'=>$sv['name'].' is now resting and available for expeditions.']);}
if($action!=='assign')json_err('bad_action','Unknown assignment action.');if((int)$sv['hp']<=0)json_err('injured','A downed survivor cannot work.');if((float)$sv['fatigue']>=90)json_err('exhausted','That survivor is too exhausted to work.');
$home=$db->query("SELECT location FROM strongholds WHERE userid=$uid")->fetch_assoc()['location'];$homePos=explode('|',$home);$member=$db->query("SELECT q.id,q.name,q.x,q.y,q.arrives_at FROM squad_members m JOIN squads q ON q.id=m.squad_id WHERE m.survivor_id=$survivor AND q.userid=$uid LIMIT 1");if($member&&$member->num_rows){$sq=$member->fetch_assoc();$away=(int)$sq['arrives_at']>time()||(int)$sq['x']!==(int)$homePos[0]||(int)$sq['y']!==(int)$homePos[1];if($away)json_err('on_expedition',$sv['name'].' is away with '.$sq['name'].'.');$db->query("DELETE FROM squad_members WHERE survivor_id=$survivor");}$training=$db->query("SELECT 1 FROM training_jobs WHERE survivor_id=$survivor LIMIT 1");if($training&&$training->num_rows)json_err('in_training','That survivor is currently training.');
$capacity=min(3,max(1,(int)ceil($level/2)));$count=$db->query("SELECT COUNT(*) n FROM survivors WHERE userid=$uid AND job_facility=$slot AND id<>$survivor")->fetch_assoc();if((int)$count['n']>=$capacity)json_err('facility_full','This facility has no free work stations.');$db->query("UPDATE survivors SET job_facility=$slot WHERE id=$survivor AND userid=$uid");
$fr=$db->query("SELECT name FROM facilities WHERE id=$slot LIMIT 1");$name=$fr&&$fr->num_rows?$fr->fetch_assoc()['name']:'facility';json_out(['ok'=>true,'message'=>$sv['name'].' assigned to '.$name.'.']);
