<?php
require __DIR__ . '/_bootstrap.php'; global $db;
$uid=api_require_user(); zv2_refresh($uid);

function force_context(int $uid):array{global $db;$h=$db->query("SELECT location,buildings,ressis FROM strongholds WHERE userid=$uid LIMIT 1")->fetch_assoc();$p=explode('|',$h['location']);$levels=pipe_nums($h['buildings']);return[(int)$p[0],(int)$p[1],(int)($levels[10]??0),(int)($levels[4]??0),(int)($levels[3]??0),pipe_nums($h['ressis'])];}
function force_squad(int $uid,int $id):array{foreach(zv2_squads($uid)as$s)if($s['id']===$id)return$s;json_err('bad_squad','Choose one of your squads.');}
function force_equipment_catalog(int $uid):array{global $db;$out=[];$r=$db->query("SELECT i.id,i.name,i.category,i.attack_bonus,i.defense_bonus,v.amount,COALESCE(personal.used,0) personal,COALESCE(squads.used,0) assigned FROM inventory v JOIN items i ON i.id=v.item_id LEFT JOIN (SELECT equipped_weapon item_id,COUNT(*) used FROM survivors WHERE userid=$uid AND equipped_weapon IS NOT NULL GROUP BY equipped_weapon) personal ON personal.item_id=i.id LEFT JOIN (SELECT se.item_id,SUM(se.amount) used FROM squad_equipment se JOIN squads q ON q.id=se.squad_id WHERE q.userid=$uid GROUP BY se.item_id) squads ON squads.item_id=i.id WHERE v.userid=$uid AND (i.attack_bonus>0 OR i.defense_bonus>0) ORDER BY i.category,i.name");while($r&&($i=$r->fetch_assoc()))$out[]=['id'=>(int)$i['id'],'name'=>$i['name'],'category'=>$i['category'],'slot'=>(int)$i['attack_bonus']>0?'weapon':'defense','owned'=>(int)$i['amount'],'personal'=>(int)$i['personal'],'assigned'=>(int)$i['assigned'],'available'=>max(0,(int)$i['amount']-(int)$i['personal']-(int)$i['assigned']),'attackBonus'=>(int)$i['attack_bonus'],'defenseBonus'=>(int)$i['defense_bonus']];return$out;}
function force_vehicle_types():array{global $db;$out=[];$r=$db->query("SELECT * FROM vehicle_types ORDER BY garage_level,id");while($r&&($v=$r->fetch_assoc()))$out[]=['id'=>(int)$v['id'],'name'=>$v['name'],'description'=>$v['description'],'garageLevel'=>(int)$v['garage_level'],'seats'=>(int)$v['seats'],'cargoBonus'=>(int)$v['cargo_bonus'],'speedBonus'=>(int)$v['speed_bonus'],'fuelCapacity'=>(int)$v['fuel_capacity'],'fuelPerTile'=>(int)$v['fuel_per_tile'],'metalCost'=>(int)$v['metal_cost'],'woodCost'=>(int)$v['wood_cost']];return$out;}
function force_vehicles(int $uid):array{global $db;$out=[];$r=$db->query("SELECT v.*,t.name type_name,t.description,t.seats,t.cargo_bonus,t.speed_bonus,t.fuel_capacity,t.fuel_per_tile,t.garage_level FROM vehicles v JOIN vehicle_types t ON t.id=v.type_id WHERE v.userid=$uid ORDER BY v.id");while($r&&($v=$r->fetch_assoc()))$out[]=['id'=>(int)$v['id'],'typeId'=>(int)$v['type_id'],'name'=>$v['name'],'type'=>$v['type_name'],'description'=>$v['description'],'fuel'=>(int)$v['fuel'],'fuelCapacity'=>(int)$v['fuel_capacity'],'fuelPerTile'=>(int)$v['fuel_per_tile'],'seats'=>(int)$v['seats']+(int)$v['seats_upgrade'],'baseSeats'=>(int)$v['seats'],'seatsUpgrade'=>(int)$v['seats_upgrade'],'cargoBonus'=>(int)$v['cargo_bonus']+(int)$v['cargo_upgrade']*10,'baseCargoBonus'=>(int)$v['cargo_bonus'],'cargoUpgrade'=>(int)$v['cargo_upgrade'],'speedBonus'=>(int)$v['speed_bonus'],'garageLevel'=>(int)$v['garage_level'],'assignedSquad'=>$v['assigned_squad']===null?null:(int)$v['assigned_squad']];return$out;}
function force_vehicle(int $uid,int $id):array{foreach(force_vehicles($uid)as$v)if($v['id']===$id)return$v;json_err('bad_vehicle','Choose one of your vehicles.');}
function force_save_resources(int $uid,array $res):void{global $db;$esc=$db->real_escape_string(implode('|',$res));$db->query("UPDATE strongholds SET ressis='$esc' WHERE userid=$uid");}

if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
 $action=(string)($_POST['action']??'');[$hx,$hy,$quarters,$storage,$garage,$resources]=force_context($uid);
 if($action==='create'){
  if($quarters<1)json_err('no_quarters','Build Troop Quarters before forming another squad.');$count=(int)$db->query("SELECT COUNT(*) n FROM squads WHERE userid=$uid")->fetch_assoc()['n'];$limit=min(5,1+$quarters);if($count>=$limit)json_err('squad_limit',"Troop Quarters level $quarters supports $limit squads.");$names=['Alpha','Bravo','Charlie','Delta','Echo'];$name=$names[$count]??('Squad '.($count+1));$db->query("INSERT INTO squads(userid,name,x,y) VALUES($uid,'$name',$hx,$hy)");json_out(['ok'=>true,'message'=>"$name formed. Assign named survivors before deployment."]);
 }
 if($action==='assign'){
  $sid=(int)($_POST['survivor']??0);$qid=(int)($_POST['squad']??0);$sq=force_squad($uid,$qid);if($sq['traveling']||$sq['x']!==$hx||$sq['y']!==$hy)json_err('squad_away','Personnel changes are only possible while the squad is at the stronghold.');$sv=$db->query("SELECT id,name,job_facility FROM survivors WHERE id=$sid AND userid=$uid AND hp>0 LIMIT 1");if(!$sv||!$sv->num_rows)json_err('bad_survivor','Choose an available survivor.');$person=$sv->fetch_assoc();if($person['job_facility']!==null)json_err('survivor_working',$person['name'].' is assigned to a facility.');if($db->query("SELECT survivor_id FROM training_jobs WHERE survivor_id=$sid")->num_rows)json_err('survivor_training',$person['name'].' is currently training.');$vehicle=zv2_squad_vehicle($uid,$qid);if($vehicle&&count($sq['crew'])+1>$vehicle['seats'])json_err('vehicle_seats',$vehicle['name'].' has no free passenger seat. Upgrade it or unassign it first.');$db->begin_transaction();try{$db->query("DELETE FROM squad_members WHERE survivor_id=$sid");$db->query("INSERT INTO squad_members(squad_id,survivor_id) VALUES($qid,$sid)");$db->commit();}catch(Throwable$e){$db->rollback();throw$e;}json_out(['ok'=>true,'message'=>$person['name'].' joined '.$sq['name'].'.']);
 }
 if($action==='remove'){
  $sid=(int)($_POST['survivor']??0);$qid=(int)($_POST['squad']??0);$sq=force_squad($uid,$qid);if($sq['traveling']||$sq['x']!==$hx||$sq['y']!==$hy)json_err('squad_away','The squad must return home before changing personnel.');$db->query("DELETE sm FROM squad_members sm JOIN survivors s ON s.id=sm.survivor_id WHERE sm.squad_id=$qid AND sm.survivor_id=$sid AND s.userid=$uid");json_out(['ok'=>true,'message'=>'Survivor returned to the stronghold reserve.']);
 }
 if($action==='return'){
  $qid=(int)($_POST['squad']??0);$sq=force_squad($uid,$qid);if($sq['traveling'])json_err('squad_traveling',$sq['name'].' is already traveling.');if($sq['x']===$hx&&$sq['y']===$hy)json_err('already_home',$sq['name'].' is already at the stronghold.');if(!$sq['crew'])json_err('no_crew','An empty squad cannot travel.');$distance=abs($sq['x']-$hx)+abs($sq['y']-$hy);$drive=zv2_vehicle_travel($uid,$qid,$distance,true,true);$speed=(zv2_tech_effects($uid)['travel_speed']??0)+$drive['speedBonus'];$seconds=max(3,(int)ceil($distance*5/(1+$speed/100)));$now=time();$db->query("UPDATE squads SET target_x=$hx,target_y=$hy,started_at=$now,arrives_at=".($now+$seconds).",last_event='' WHERE id=$qid AND userid=$uid");$note=$drive['emergency']?' The empty vehicle is being brought back at foot pace.':($drive['vehicle']?' '.$drive['vehicle']['name'].' used '.$drive['fuelUsed'].' fuel.':'');json_out(['ok'=>true,'message'=>$sq['name'].' is returning home with its cargo.'.$note,'travel'=>['seconds'=>$seconds,'arrivesAt'=>$now+$seconds,'vehicle'=>$drive['vehicle'],'fuelUsed'=>$drive['fuelUsed'],'emergency'=>$drive['emergency']]]);
 }
 if($action==='deposit'){
  $qid=(int)($_POST['squad']??0);$sq=force_squad($uid,$qid);if($sq['traveling']||$sq['x']!==$hx||$sq['y']!==$hy)json_err('squad_away','The squad must be at the stronghold to deposit loot.');if($storage<1)json_err('no_storage','Build a Storage before depositing squad loot.');$cargo=zv2_squad_cargo($qid);if(!$cargo['items'])json_err('no_cargo',$sq['name'].' has no loot to deposit.');$count=array_sum(array_column($cargo['items'],'amount'));$db->begin_transaction();try{foreach($cargo['items']as$item)zv2_add_item($uid,$item['id'],$item['amount']);$db->query("DELETE FROM squad_cargo WHERE squad_id=$qid");$message=$sq['name'].' deposited '.$count.' carried items in Storage.';$escaped=$db->real_escape_string($message);$db->query("INSERT INTO squad_events(squad_id,event_type,message,created_at) VALUES($qid,'deposit','$escaped',".time().")");$db->query("UPDATE squads SET last_event='$escaped' WHERE id=$qid AND userid=$uid");$db->commit();}catch(Throwable$e){$db->rollback();throw$e;}json_out(['ok'=>true,'message'=>$message,'cargo'=>zv2_squad_cargo($qid)]);
 }
 if($action==='equip'||$action==='unequip'){
  $qid=(int)($_POST['squad']??0);$item=(int)($_POST['item']??0);$sq=force_squad($uid,$qid);if($sq['traveling']||$sq['x']!==$hx||$sq['y']!==$hy)json_err('squad_away','Squad equipment can only be changed at the stronghold.');$catalog=force_equipment_catalog($uid);$gear=null;foreach($catalog as$c)if($c['id']===$item)$gear=$c;if(!$gear)json_err('bad_equipment','Choose a weapon or defense item from Storage.');
  if($action==='equip'){if($storage<1)json_err('no_storage','Build Storage before issuing squad equipment.');if(!$sq['crew'])json_err('no_crew','Assign survivors before equipping this squad.');if($gear['available']<1)json_err('equipment_unavailable',$gear['name'].' is already assigned or equipped.');$load=$sq['equipment'];$slots=$load['slots'][$gear['slot']==='weapon'?'weapons':'defense'];if($slots['used']>=$slots['capacity'])json_err('equipment_slots_full','No free '.$gear['slot'].' slots in '.$sq['name'].'.');$db->query("INSERT INTO squad_equipment(squad_id,item_id,amount) VALUES($qid,$item,1) ON DUPLICATE KEY UPDATE amount=amount+1");json_out(['ok'=>true,'message'=>$gear['name'].' equipped by '.$sq['name'].'.']);}
  $owned=$db->query("SELECT amount FROM squad_equipment WHERE squad_id=$qid AND item_id=$item LIMIT 1");if(!$owned||!$owned->num_rows)json_err('not_equipped',$gear['name'].' is not equipped by this squad.');$amount=(int)$owned->fetch_assoc()['amount'];if($amount<=1)$db->query("DELETE FROM squad_equipment WHERE squad_id=$qid AND item_id=$item");else$db->query("UPDATE squad_equipment SET amount=amount-1 WHERE squad_id=$qid AND item_id=$item");json_out(['ok'=>true,'message'=>$gear['name'].' returned to Storage.']);
 }
 if($action==='vehicle_restore'){
  $typeId=(int)($_POST['item']??0);$type=null;foreach(force_vehicle_types()as$t)if($t['id']===$typeId)$type=$t;if(!$type)json_err('bad_vehicle_type','Choose a vehicle design.');if($garage<$type['garageLevel'])json_err('garage_level','Garage level '.$type['garageLevel'].' is required to restore '.$type['name'].'.');if(($resources[3]??0)<$type['metalCost']||($resources[2]??0)<$type['woodCost'])json_err('vehicle_resources','Restoring '.$type['name'].' requires '.$type['metalCost'].' metal and '.$type['woodCost'].' wood.');$resources[3]-=$type['metalCost'];$resources[2]-=$type['woodCost'];$name=$db->real_escape_string($type['name'].' #'.((int)$db->query("SELECT COUNT(*) n FROM vehicles WHERE userid=$uid")->fetch_assoc()['n']+1));$fuel=(int)ceil($type['fuelCapacity']/4);$db->begin_transaction();try{force_save_resources($uid,$resources);$db->query("INSERT INTO vehicles(userid,type_id,name,fuel,created_at) VALUES($uid,$typeId,'$name',$fuel,".time().")");$db->commit();}catch(Throwable$e){$db->rollback();throw$e;}json_out(['ok'=>true,'message'=>$type['name'].' restored in the Garage with '.$fuel.' fuel.']);
 }
 if(in_array($action,['vehicle_assign','vehicle_unassign','vehicle_refuel','vehicle_upgrade'],true)){
  $vehicleId=(int)($_POST['item']??0);$vehicle=force_vehicle($uid,$vehicleId);$qid=(int)($_POST['squad']??0);$sq=$qid?force_squad($uid,$qid):null;
  if($action==='vehicle_assign'){if(!$sq)json_err('bad_squad','Choose a squad.');if($garage<1)json_err('no_garage','Build a Garage before assigning vehicles.');if($sq['traveling']||$sq['x']!==$hx||$sq['y']!==$hy)json_err('squad_away','Vehicles can only be assigned at the stronghold.');if($vehicle['assignedSquad']!==null)json_err('vehicle_assigned',$vehicle['name'].' is already assigned.');if(count($sq['crew'])>$vehicle['seats'])json_err('vehicle_seats',$vehicle['name'].' has '.$vehicle['seats'].' seats for '.count($sq['crew']).' squad members.');$db->query("UPDATE vehicles SET assigned_squad=$qid WHERE id=$vehicleId AND userid=$uid");json_out(['ok'=>true,'message'=>$vehicle['name'].' assigned to '.$sq['name'].'.']);}
  if($action==='vehicle_unassign'){if(!$sq||$vehicle['assignedSquad']!==$qid)json_err('vehicle_squad','That vehicle is not assigned to this squad.');if($sq['traveling']||$sq['x']!==$hx||$sq['y']!==$hy)json_err('squad_away','The squad must return home before releasing its vehicle.');$cargo=$sq['cargo'];$foot=$cargo['footCapacity'];if($cargo['used']>$foot)json_err('vehicle_cargo','Unload cargo until it fits the squad\'s '.$foot.' kg foot capacity.');$db->query("UPDATE vehicles SET assigned_squad=NULL WHERE id=$vehicleId AND userid=$uid");json_out(['ok'=>true,'message'=>$vehicle['name'].' returned to the Garage.']);}
  if($action==='vehicle_refuel'){if($garage<1)json_err('no_garage','Build a Garage before refuelling vehicles.');if($vehicle['assignedSquad']!==null){$vs=force_squad($uid,$vehicle['assignedSquad']);if($vs['traveling']||$vs['x']!==$hx||$vs['y']!==$hy)json_err('vehicle_away','The vehicle must be at the stronghold to refuel.');}$need=max(0,$vehicle['fuelCapacity']-$vehicle['fuel']);if(!$need)json_err('fuel_full',$vehicle['name'].' already has a full tank.');$take=min($need,(int)floor($resources[4]??0));if($take<1)json_err('no_petrol','The stronghold has no petrol for the Garage.');$resources[4]-=$take;$db->begin_transaction();try{force_save_resources($uid,$resources);$db->query("UPDATE vehicles SET fuel=fuel+$take WHERE id=$vehicleId AND userid=$uid");$db->commit();}catch(Throwable$e){$db->rollback();throw$e;}json_out(['ok'=>true,'message'=>$vehicle['name'].' refuelled by '.$take.' units.']);}
  $kind=(string)($_POST['focus']??'');if(!in_array($kind,['seats','cargo'],true))json_err('bad_vehicle_upgrade','Choose a seat or cargo upgrade.');$current=$kind==='seats'?$vehicle['seatsUpgrade']:$vehicle['cargoUpgrade'];$limit=$kind==='seats'?2:3;if($current>=$limit)json_err('vehicle_upgrade_max','That '.$kind.' upgrade is already complete.');$required=$vehicle['garageLevel']+$current;if($garage<$required)json_err('garage_level','Garage level '.$required.' is required for the next '.$kind.' upgrade.');$metal=20+($current+1)*15;$wood=10+($current+1)*5;if(($resources[3]??0)<$metal||($resources[2]??0)<$wood)json_err('vehicle_resources','This upgrade requires '.$metal.' metal and '.$wood.' wood.');if($vehicle['assignedSquad']!==null){$vs=force_squad($uid,$vehicle['assignedSquad']);if($vs['traveling']||$vs['x']!==$hx||$vs['y']!==$hy)json_err('vehicle_away','The vehicle must be at the stronghold for upgrades.');}$resources[3]-=$metal;$resources[2]-=$wood;$field=$kind==='seats'?'seats_upgrade':'cargo_upgrade';$db->begin_transaction();try{force_save_resources($uid,$resources);$db->query("UPDATE vehicles SET $field=$field+1 WHERE id=$vehicleId AND userid=$uid");$db->commit();}catch(Throwable$e){$db->rollback();throw$e;}json_out(['ok'=>true,'message'=>$vehicle['name'].' received a '.$kind.' upgrade.']);
 }
 if($action==='train'){
  if($quarters<1)json_err('no_quarters','Build Troop Quarters to train survivors.');$sid=(int)($_POST['survivor']??0);$focus=(string)($_POST['focus']??'');if(!in_array($focus,['attack','defense'],true))json_err('bad_focus','Choose combat or defence training.');$cap=min(3,max(1,(int)ceil($quarters/2)));$busy=(int)$db->query("SELECT COUNT(*) n FROM training_jobs WHERE userid=$uid")->fetch_assoc()['n'];if($busy>=$cap)json_err('training_full','All training slots are occupied.');$sv=$db->query("SELECT s.id,s.name,s.job_facility,sm.survivor_id squad_member FROM survivors s LEFT JOIN squad_members sm ON sm.survivor_id=s.id WHERE s.id=$sid AND s.userid=$uid AND s.hp>0 LIMIT 1");if(!$sv||!$sv->num_rows)json_err('bad_survivor','Choose an available survivor.');$person=$sv->fetch_assoc();if($person['job_facility']!==null||$person['squad_member']!==null)json_err('survivor_busy',$person['name'].' must be in reserve to train.');$seconds=max(15,45-$quarters*5);$now=time();$db->query("INSERT INTO training_jobs(survivor_id,userid,focus,due,started_at) VALUES($sid,$uid,'$focus',".($now+$seconds).",$now)");json_out(['ok'=>true,'message'=>$person['name'].' started '.$focus.' training.']);
 }
 json_err('bad_action','Unknown forces action.');
}

[$hx,$hy,$quarters,$storage,$garage,$resources]=force_context($uid);$squads=zv2_squads($uid);$squadNames=[];foreach($squads as$s)$squadNames[$s['id']]=$s['name'];$survivors=[];$q=$db->query("SELECT s.id,s.name,s.hp,s.max_hp,s.attack_stat,s.defense_stat,s.equipped_weapon,s.job_facility,s.fatigue,i.name weapon,sm.squad_id,t.focus,t.due,ht.started_at treatment_started,ht.due treatment_due,ht.soldier_level,ht.hospital_level FROM survivors s LEFT JOIN items i ON i.id=s.equipped_weapon LEFT JOIN squad_members sm ON sm.survivor_id=s.id LEFT JOIN training_jobs t ON t.survivor_id=s.id LEFT JOIN hospital_treatments ht ON ht.survivor_id=s.id WHERE s.userid=$uid ORDER BY s.name");while($q&&($v=$q->fetch_assoc()))$survivors[]=['id'=>(int)$v['id'],'name'=>$v['name'],'hp'=>(int)$v['hp'],'maxHp'=>(int)$v['max_hp'],'attack'=>(int)$v['attack_stat'],'defense'=>(int)$v['defense_stat'],'level'=>zv2_soldier_level($v),'fatigue'=>(int)$v['fatigue'],'weapon'=>$v['weapon'],'squadId'=>$v['squad_id']===null?null:(int)$v['squad_id'],'squad'=>$v['squad_id']===null?null:($squadNames[(int)$v['squad_id']]??null),'job'=>$v['job_facility']===null?null:(int)$v['job_facility'],'training'=>$v['focus']?['focus'=>$v['focus'],'due'=>(int)$v['due']]:null,'treatment'=>$v['treatment_due']===null?null:['startedAt'=>(int)$v['treatment_started'],'due'=>(int)$v['treatment_due'],'soldierLevel'=>(int)$v['soldier_level'],'hospitalLevel'=>(int)$v['hospital_level']]];$rq=$db->query("SELECT COUNT(*) total,SUM(found_at>0) found FROM recruit_encounters WHERE userid=$uid")->fetch_assoc();json_out(['ok'=>true,'quarters'=>['level'=>$quarters,'squadLimit'=>min(5,1+$quarters),'trainingCapacity'=>$quarters?min(3,max(1,(int)ceil($quarters/2))):0],'storage'=>['level'=>$storage,'acceptsLoot'=>$storage>0],'garage'=>['level'=>$garage,'petrol'=>(int)floor($resources[4]??0),'metal'=>(int)floor($resources[3]??0),'wood'=>(int)floor($resources[2]??0)],'home'=>['x'=>$hx,'y'=>$hy],'squads'=>$squads,'survivors'=>$survivors,'equipmentCatalog'=>force_equipment_catalog($uid),'vehicleTypes'=>force_vehicle_types(),'vehicles'=>force_vehicles($uid),'recruits'=>['found'=>(int)$rq['found'],'total'=>(int)$rq['total']]]);
