<?php
require __DIR__ . '/_bootstrap.php'; global $db;
$uid=api_require_user(); zv2_refresh($uid);

function force_context(int $uid):array{global $db;$h=$db->query("SELECT location,buildings FROM strongholds WHERE userid=$uid LIMIT 1")->fetch_assoc();$p=explode('|',$h['location']);$levels=pipe_nums($h['buildings']);$quarters=(int)($levels[10]??0);$storage=(int)($levels[4]??0);return[(int)$p[0],(int)$p[1],$quarters,$storage];}
function force_squad(int $uid,int $id):array{foreach(zv2_squads($uid)as$s)if($s['id']===$id)return$s;json_err('bad_squad','Choose one of your squads.');}

if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
 $action=(string)($_POST['action']??'');[$hx,$hy,$quarters]=force_context($uid);
 if($action==='create'){
  if($quarters<1)json_err('no_quarters','Build Troop Quarters before forming another squad.');$count=(int)$db->query("SELECT COUNT(*) n FROM squads WHERE userid=$uid")->fetch_assoc()['n'];$limit=min(5,1+$quarters);if($count>=$limit)json_err('squad_limit',"Troop Quarters level $quarters supports $limit squads.");$names=['Alpha','Bravo','Charlie','Delta','Echo'];$name=$names[$count]??('Squad '.($count+1));$db->query("INSERT INTO squads(userid,name,x,y) VALUES($uid,'$name',$hx,$hy)");json_out(['ok'=>true,'message'=>"$name formed. Assign named survivors before deployment."]);
 }
 if($action==='assign'){
  $sid=(int)($_POST['survivor']??0);$qid=(int)($_POST['squad']??0);$sq=force_squad($uid,$qid);if($sq['traveling']||$sq['x']!==$hx||$sq['y']!==$hy)json_err('squad_away','Personnel changes are only possible while the squad is at the stronghold.');$sv=$db->query("SELECT id,name,job_facility FROM survivors WHERE id=$sid AND userid=$uid AND hp>0 LIMIT 1");if(!$sv||!$sv->num_rows)json_err('bad_survivor','Choose an available survivor.');$person=$sv->fetch_assoc();if($person['job_facility']!==null)json_err('survivor_working',$person['name'].' is assigned to a facility.');if($db->query("SELECT survivor_id FROM training_jobs WHERE survivor_id=$sid")->num_rows)json_err('survivor_training',$person['name'].' is currently training.');$db->begin_transaction();try{$db->query("DELETE FROM squad_members WHERE survivor_id=$sid");$db->query("INSERT INTO squad_members(squad_id,survivor_id) VALUES($qid,$sid)");$db->commit();}catch(Throwable$e){$db->rollback();throw$e;}json_out(['ok'=>true,'message'=>$person['name'].' joined '.$sq['name'].'.']);
 }
 if($action==='remove'){
  $sid=(int)($_POST['survivor']??0);$qid=(int)($_POST['squad']??0);$sq=force_squad($uid,$qid);if($sq['traveling']||$sq['x']!==$hx||$sq['y']!==$hy)json_err('squad_away','The squad must return home before changing personnel.');$db->query("DELETE sm FROM squad_members sm JOIN survivors s ON s.id=sm.survivor_id WHERE sm.squad_id=$qid AND sm.survivor_id=$sid AND s.userid=$uid");json_out(['ok'=>true,'message'=>'Survivor returned to the stronghold reserve.']);
 }
 if($action==='return'){
  $qid=(int)($_POST['squad']??0);$sq=force_squad($uid,$qid);if($sq['traveling'])json_err('squad_traveling',$sq['name'].' is already traveling.');if($sq['x']===$hx&&$sq['y']===$hy)json_err('already_home',$sq['name'].' is already at the stronghold.');if(!$sq['crew'])json_err('no_crew','An empty squad cannot travel.');$distance=abs($sq['x']-$hx)+abs($sq['y']-$hy);$speed=zv2_tech_effects($uid)['travel_speed']??0;$seconds=max(3,(int)ceil($distance*5/(1+$speed/100)));$now=time();$db->query("UPDATE squads SET target_x=$hx,target_y=$hy,started_at=$now,arrives_at=".($now+$seconds).",last_event='' WHERE id=$qid AND userid=$uid");json_out(['ok'=>true,'message'=>$sq['name'].' is returning home with its cargo.','travel'=>['seconds'=>$seconds,'arrivesAt'=>$now+$seconds]]);
 }
 if($action==='train'){
  if($quarters<1)json_err('no_quarters','Build Troop Quarters to train survivors.');$sid=(int)($_POST['survivor']??0);$focus=(string)($_POST['focus']??'');if(!in_array($focus,['attack','defense'],true))json_err('bad_focus','Choose combat or defence training.');$cap=min(3,max(1,(int)ceil($quarters/2)));$busy=(int)$db->query("SELECT COUNT(*) n FROM training_jobs WHERE userid=$uid")->fetch_assoc()['n'];if($busy>=$cap)json_err('training_full','All training slots are occupied.');$sv=$db->query("SELECT s.id,s.name,s.job_facility,sm.survivor_id squad_member FROM survivors s LEFT JOIN squad_members sm ON sm.survivor_id=s.id WHERE s.id=$sid AND s.userid=$uid AND s.hp>0 LIMIT 1");if(!$sv||!$sv->num_rows)json_err('bad_survivor','Choose an available survivor.');$person=$sv->fetch_assoc();if($person['job_facility']!==null||$person['squad_member']!==null)json_err('survivor_busy',$person['name'].' must be in reserve to train.');$seconds=max(15,45-$quarters*5);$now=time();$db->query("INSERT INTO training_jobs(survivor_id,userid,focus,due,started_at) VALUES($sid,$uid,'$focus',".($now+$seconds).",$now)");json_out(['ok'=>true,'message'=>$person['name'].' started '.$focus.' training.']);
 }
 json_err('bad_action','Unknown forces action.');
}

[$hx,$hy,$quarters,$storage]=force_context($uid);$squads=zv2_squads($uid);$squadNames=[];foreach($squads as$s)$squadNames[$s['id']]=$s['name'];$survivors=[];$q=$db->query("SELECT s.id,s.name,s.hp,s.max_hp,s.attack_stat,s.defense_stat,s.equipped_weapon,s.job_facility,s.fatigue,i.name weapon,sm.squad_id,t.focus,t.due FROM survivors s LEFT JOIN items i ON i.id=s.equipped_weapon LEFT JOIN squad_members sm ON sm.survivor_id=s.id LEFT JOIN training_jobs t ON t.survivor_id=s.id WHERE s.userid=$uid ORDER BY s.name");while($q&&($v=$q->fetch_assoc()))$survivors[]=['id'=>(int)$v['id'],'name'=>$v['name'],'hp'=>(int)$v['hp'],'maxHp'=>(int)$v['max_hp'],'attack'=>(int)$v['attack_stat'],'defense'=>(int)$v['defense_stat'],'fatigue'=>(int)$v['fatigue'],'weapon'=>$v['weapon'],'squadId'=>$v['squad_id']===null?null:(int)$v['squad_id'],'squad'=>$v['squad_id']===null?null:($squadNames[(int)$v['squad_id']]??null),'job'=>$v['job_facility']===null?null:(int)$v['job_facility'],'training'=>$v['focus']?['focus'=>$v['focus'],'due'=>(int)$v['due']]:null];$rq=$db->query("SELECT COUNT(*) total,SUM(found_at>0) found FROM recruit_encounters WHERE userid=$uid")->fetch_assoc();json_out(['ok'=>true,'quarters'=>['level'=>$quarters,'squadLimit'=>min(5,1+$quarters),'trainingCapacity'=>$quarters?min(3,max(1,(int)ceil($quarters/2))):0],'storage'=>['level'=>$storage,'acceptsLoot'=>$storage>0],'home'=>['x'=>$hx,'y'=>$hy],'squads'=>$squads,'survivors'=>$survivors,'recruits'=>['found'=>(int)$rq['found'],'total'=>(int)$rq['total']]]);
