<?php
require __DIR__ . '/_bootstrap.php';global $db;$uid=api_require_user();if(($_SERVER['REQUEST_METHOD']??'GET')!=='POST')json_err('method','POST required',405);
$action=(string)($_POST['action']??'');$survivor=(int)($_POST['survivor']??0);$item=(int)($_POST['item']??0);
$sr=$db->query("SELECT id,hp,max_hp FROM survivors WHERE id=$survivor AND userid=$uid LIMIT 1");if(!$sr||!$sr->num_rows)json_err('bad_survivor','Choose one of your survivors.');$sv=$sr->fetch_assoc();
if($db->query("SELECT survivor_id FROM hospital_treatments WHERE survivor_id=$survivor AND userid=$uid")->num_rows)json_err('in_treatment','This survivor is receiving Hospital treatment.');
$member=$db->query("SELECT q.name,q.x,q.y,q.target_x,q.target_y,q.arrives_at,h.location FROM squad_members sm JOIN squads q ON q.id=sm.squad_id JOIN strongholds h ON h.userid=q.userid WHERE sm.survivor_id=$survivor AND q.userid=$uid LIMIT 1");if($member&&$member->num_rows&&in_array($action,['equip','use','repair'],true)){$squad=$member->fetch_assoc();[$hx,$hy]=array_map('intval',explode('|',$squad['location']));$now=time();$traveling=(int)$squad['arrives_at']>$now;$arrived=(int)$squad['arrives_at']>0&&(int)$squad['arrives_at']<=$now&&$squad['target_x']!==null;$sx=$arrived?(int)$squad['target_x']:(int)$squad['x'];$sy=$arrived?(int)$squad['target_y']:(int)$squad['y'];if($traveling||$sx!==$hx||$sy!==$hy)json_err('squad_away',$squad['name'].' can only use items carried in its own cargo while outside the compound.');}
if($action==='equip'){$ir=$db->query("SELECT v.amount,i.category,i.name FROM inventory v JOIN items i ON i.id=v.item_id WHERE v.userid=$uid AND v.item_id=$item LIMIT 1");if(!$ir||!$ir->num_rows)json_err('not_owned','You do not own that item.');$it=$ir->fetch_assoc();if($it['category']!=='weapon')json_err('not_weapon','Only weapons can be equipped here.');$personal=$db->query("SELECT COUNT(*) n FROM survivors WHERE userid=$uid AND equipped_weapon=$item AND id<>$survivor")->fetch_assoc();$assigned=$db->query("SELECT COALESCE(SUM(se.amount),0) n FROM squad_equipment se JOIN squads q ON q.id=se.squad_id WHERE q.userid=$uid AND se.item_id=$item")->fetch_assoc();if((int)$personal['n']+(int)$assigned['n']>=(int)$it['amount'])json_err('already_equipped','All copies are already assigned to survivors or squads.');$db->query("UPDATE survivors SET equipped_weapon=$item WHERE id=$survivor AND userid=$uid");json_out(['ok'=>true,'message'=>$it['name'].' equipped by survivor.']);}
if($action==='unequip'){$db->query("UPDATE survivors SET equipped_weapon=NULL WHERE id=$survivor AND userid=$uid");json_out(['ok'=>true,'message'=>'Weapon unequipped.']);}
if($action==='use'){$ir=$db->query("SELECT v.amount,i.name,i.healing FROM inventory v JOIN items i ON i.id=v.item_id WHERE v.userid=$uid AND v.item_id=$item LIMIT 1");if(!$ir||!$ir->num_rows)json_err('not_owned','You do not own that item.');$it=$ir->fetch_assoc();$hr=$db->query("SELECT buildings FROM strongholds WHERE userid=$uid LIMIT 1");$levels=$hr&&$hr->num_rows?pipe_nums($hr->fetch_assoc()['buildings']):[];$effects=zv2_staff_effects($uid,$levels);$heal=(int)$it['healing']+$effects['medical']+(int)($effects['tech']['healing_bonus']??0);if($heal<=0)json_err('not_usable','That item cannot be used this way.');if((int)$sv['hp']>=(int)$sv['max_hp'])json_err('full_health','That survivor is already at full health.');$new=min((int)$sv['max_hp'],(int)$sv['hp']+$heal);$db->begin_transaction();try{$db->query("UPDATE survivors SET hp=$new WHERE id=$survivor AND userid=$uid");$db->query("UPDATE inventory SET amount=amount-1 WHERE userid=$uid AND item_id=$item");$db->query("DELETE FROM inventory WHERE userid=$uid AND item_id=$item AND amount<=0");$db->commit();}catch(Throwable$e){$db->rollback();throw$e;}json_out(['ok'=>true,'message'=>$it['name'].' restored '.($new-(int)$sv['hp']).' health.']);}
if($action==='repair'){$wr=$db->query("SELECT s.equipped_weapon,v.durability,i.max_durability FROM survivors s JOIN items i ON i.id=s.equipped_weapon JOIN inventory v ON v.userid=s.userid AND v.item_id=s.equipped_weapon WHERE s.id=$survivor AND s.userid=$uid LIMIT 1");if(!$wr||!$wr->num_rows)json_err('no_weapon','Equip a weapon first.');$weapon=$wr->fetch_assoc();if((int)$weapon['durability']>=(int)$weapon['max_durability'])json_err('full_condition','That weapon does not need repairs.');$kr=$db->query("SELECT v.amount,i.name,i.repair_amount FROM inventory v JOIN items i ON i.id=v.item_id WHERE v.userid=$uid AND v.item_id=$item LIMIT 1");if(!$kr||!$kr->num_rows)json_err('not_owned','You do not own that repair item.');$kit=$kr->fetch_assoc();if((int)$kit['repair_amount']<=0)json_err('not_repair','That item cannot repair weapons.');$new=min((int)$weapon['max_durability'],(int)$weapon['durability']+(int)$kit['repair_amount']);$db->begin_transaction();try{$db->query("UPDATE inventory SET durability=$new WHERE userid=$uid AND item_id=".(int)$weapon['equipped_weapon']);$db->query("UPDATE inventory SET amount=amount-1 WHERE userid=$uid AND item_id=$item");$db->query("DELETE FROM inventory WHERE userid=$uid AND item_id=$item AND amount<=0");$db->commit();}catch(Throwable$e){$db->rollback();throw$e;}json_out(['ok'=>true,'message'=>$kit['name'].' restored weapon condition to '.$new.'/'.$weapon['max_durability'].'.']);}
json_err('bad_action','Unknown inventory action.');
