<?php
// Name pool preserved from the original Zombilization npc_names table.
// Zv2 combines one first name and one surname deterministically per player so
// saves are reproducible while different strongholds still meet different NPCs.
const ZV2_NPC_MALE_NAMES = ['John','Stephen','Ash','Marcus','Ben','Peter','Roger','Steve','Chris','Jack','Roy','Rick','William','Alex','Christopher','Megan','Philip','Dennis','Douglas','Ronny','Michael','Jeremy','Dave','Jan','Glenn','Malcolm','Charles','James','Bob','Will','John','Ron','Marty','Billy','Eric','Sam','Tim','Jason','Colin','David','Robert','Shaun','Stanley','Dale','Luke','Sam','Duncan','Vladimir','Nico','Henry','Jack','John','Thomas','Max','Ivan','Jan','Ted','Joel','Rob','Michael','Ethan','Carl','Steve','Johnny','Gary','Samuel','Luke','Aaron','Elijah','Paul','Peter','Jonathan','Tyrone','Nestor','Francis','Stringer','Marlo','Omar','Rick','Eli','Cormac','Robinette'];
const ZV2_NPC_FEMALE_NAMES = ['Ashley','Diane','Julie','Alia','Nelly','Francine','Emma','Christa','Chloe','Rachael','Sarah','Gabriela','Anna','Stephanie','Alex','Kim','Sharon','Donna','Christina','Claudine','Frances','Jill','Shirley','Julie','Jessica','Kathy','Julianne','Rebecca','Mary','Maria','Jeanne','Lily','Helen','Hannah','Liv','Eva','Liz','Nicola','Amy','Alison','Christine','Brittany','Alicia','Jane','Jeanne','Judy','Sheila','Linda','Tuesday','Lois','Epiphany','Leah','Esther','Elizabeth','Elisha','Morgan','Abigail','Sierra','Julie','Zoe','Lilith','Lori','Andrea','Olivia','Dana','Emily'];
const ZV2_NPC_SURNAMES = ['Helsing','Basilone','Bishop','Deckard','Bauer','Cusack','Sebastian','Tyrell','Smith','Quaid','Johnson','Robinson','Norris','Bowman','Poole','Floyd','Bates','Raynor','Ellis','Freck','Trejo','Lloyd','Sanderson','Ripley','McPeck','Chalmers','Bennett','Gilbert','Welles','Ronan','Cole','Hawkins','Hunter','Ballard','Werner','Kriechbaum','Bumstead','Gallagher','Hamilton','Johnston','Mills','Ashfield','Glover','McLane','Ellison','Hayden','Barry','Ripper','Randolph',"O'Hara",'Dalton','Milos','Nance','Vance','Ferrer','Dixon','Frost','Garland','Marvin','Oakland','Columbus','Goodwin','Robinson','Mills','Brooks','Landon','Verbeek','Thomas','Anderson','Abercrombie','Campbell','Foster','Prendergast','Keith','Duke','Person','Patrolman','Protagonist','Smith','Parker','Tillman','Chase','Crews','Moore','Rhodes','Kaufman','Cooper','Bronson','Rifo','Owens','Heard','Larra','Mirelurk','Harkkonen','Bell','Bolander','Carcetti','Dylath-Leen','Bowman','Enttemoss','Ferency','Glyptal','Ammenetik'];

function zv2_npc_names(int $seed,int $count):array{
    $count=max(0,min($count,count(ZV2_NPC_SURNAMES)));$male=array_values(array_unique(ZV2_NPC_MALE_NAMES));$female=array_values(array_unique(ZV2_NPC_FEMALE_NAMES));$surnames=array_values(array_unique(ZV2_NPC_SURNAMES));$out=[];
    for($i=0;$i<$count;$i++){$firsts=(($seed+$i*17)%2===0)?$female:$male;$first=$firsts[abs(($seed*31+$i*19)%count($firsts))];$surnameIndex=abs(($seed*47+$i*29)%count($surnames));while(isset($out[$first.' '.$surnames[$surnameIndex]]))$surnameIndex=($surnameIndex+1)%count($surnames);$name=$first.' '.$surnames[$surnameIndex];$out[$name]=true;}
    return array_keys($out);
}
