<?php
require __DIR__.'/_bootstrap.php';global $db;$uid=api_require_user();if(($_SERVER['REQUEST_METHOD']??'GET')!=='POST')json_err('method','POST required',405);
$action=(string)($_POST['action']??'');$encounterId=(int)($_POST['encounter']??0);$squadId=(int)($_POST['squad']??0);if(!in_array($action,['info','recruit'],true)||$encounterId<=0)json_err('bad_action','Choose a recruitment response.');
$squad=zv2_squad($uid,$squadId);if($squad['traveling'])json_err('squad_traveling','The squad must finish traveling first.');
$q=$db->query("SELECT r.*,i.name item_name,i.category FROM recruit_encounters r LEFT JOIN items i ON i.id=r.required_item WHERE r.id=$encounterId AND r.userid=$uid LIMIT 1");if(!$q||!$q->num_rows)json_err('no_encounter','That survivor is no longer here.',404);$r=$q->fetch_assoc();if((int)$r['found_at'])json_err('already_recruited',$r['name'].' already joined the stronghold.');if(!(int)$r['met_at']||(int)$r['x']!==$squad['x']||(int)$r['y']!==$squad['y'])json_err('squad_elsewhere','The recruiting squad must be with this survivor.');
$itemId=(int)$r['required_item'];if($action==='info'){
 $best=null;$rooms=$db->query("SELECT b.x,b.y,t.name building_type,rm.inventory FROM roommap rm JOIN buildings b ON b.id=rm.buildingid LEFT JOIN buildingtypes t ON t.id=b.typ WHERE rm.inventory<>''");while($rooms&&($room=$rooms->fetch_assoc())){$has=false;foreach(explode('&',(string)$room['inventory'])as$entry){$bits=explode('|',$entry);if((int)($bits[0]??0)===$itemId&&(int)($bits[1]??0)>0){$has=true;break;}}if(!$has)continue;$d=abs((int)$room['x']-$squad['x'])+abs((int)$room['y']-$squad['y']);if($best===null||$d<$best['distance'])$best=['x'=>(int)$room['x'],'y'=>(int)$room['y'],'distance'=>$d,'type'=>$room['building_type']?:'building'];}
 if($best){$dx=$best['x']-$squad['x'];$dy=$best['y']-$squad['y'];$vertical=$dy<0?'north':($dy>0?'south':'');$horizontal=$dx<0?'west':($dx>0?'east':'');$direction=$vertical&&$horizontal?$vertical.'-'.$horizontal:($vertical?:($horizontal?:'nearby'));$range=$best['distance']<=4?'a few blocks':($best['distance']<=10?'several blocks':'a long way');$hint='I heard about a '.$best['type'].' '.$range.' to the '.$direction.'. Search it carefully.';}else $hint='Try pharmacies, stores and abandoned supply rooms. Someone in this city must still have '.$r['item_name'].'.';
 json_out(['ok'=>true,'action'=>'info','hint'=>$hint]);
}
$db->begin_transaction();try{$cargo=$db->query("SELECT amount FROM squad_cargo WHERE squad_id=".(int)$squad['id']." AND item_id=$itemId FOR UPDATE");if(!$cargo||!$cargo->num_rows||(int)$cargo->fetch_assoc()['amount']<1)throw new RuntimeException('missing');$locked=$db->query("SELECT found_at FROM recruit_encounters WHERE id=$encounterId AND userid=$uid FOR UPDATE")->fetch_assoc();if((int)$locked['found_at'])throw new RuntimeException('joined');$name=$db->real_escape_string($r['name']);$hp=10+(int)$r['defense_stat'];$db->query("UPDATE squad_cargo SET amount=amount-1 WHERE squad_id=".(int)$squad['id']." AND item_id=$itemId");$db->query("DELETE FROM squad_cargo WHERE squad_id=".(int)$squad['id']." AND item_id=$itemId AND amount<=0");$db->query("INSERT INTO survivors(userid,name,hp,max_hp,attack_stat,defense_stat) VALUES($uid,'$name',$hp,$hp,".(int)$r['attack_stat'].",".(int)$r['defense_stat'].")");$survivor=(int)$db->insert_id;$now=time();$db->query("UPDATE recruit_encounters SET found_at=$now,joined_survivor=$survivor WHERE id=$encounterId AND userid=$uid");$message=$r['name'].' accepted '.$r['item_name'].' and joined the Stronghold reserve.';$me=$db->real_escape_string($message);$db->query("INSERT INTO squad_events(squad_id,event_type,message,created_at) VALUES(".(int)$squad['id'].",'recruit','$me',$now)");$db->commit();json_out(['ok'=>true,'action'=>'recruit','name'=>$r['name'],'message'=>$message]);}catch(RuntimeException$e){$db->rollback();if($e->getMessage()==='missing')json_err('item_missing','This squad is not carrying '.$r['item_name'].'.');json_err('already_recruited',$r['name'].' already joined the stronghold.');}catch(Throwable$e){$db->rollback();throw$e;}
