<?php
require __DIR__ . '/_bootstrap.php';global $db;$uid=api_require_user();zv2_refresh($uid);
$sh=$db->query("SELECT buildings FROM strongholds WHERE userid=$uid LIMIT 1")->fetch_assoc();$buildings=pipe_nums($sh['buildings']);$center=(int)($buildings[12]??0);zv2_refresh_research($uid,$buildings);
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
 $tech=(int)($_POST['tech']??0);$tq=$db->query("SELECT * FROM technologies WHERE id=$tech LIMIT 1");if(!$tq||!$tq->num_rows)json_err('bad_tech','Unknown technology.');$t=$tq->fetch_assoc();if($center<=0)json_err('no_center','Construct a Research center first.');if($center<(int)$t['center_level'])json_err('center_level','Research center level '.(int)$t['center_level'].' required.');if(zv2_has_tech($uid,$tech))json_err('completed','That technology is already recovered.');if((int)$t['prereq_id']&&!zv2_has_tech($uid,(int)$t['prereq_id']))json_err('prerequisite','Recover the previous technology in this branch first.');$busy=$db->query("SELECT 1 FROM research_jobs WHERE userid=$uid LIMIT 1");if($busy&&$busy->num_rows)json_err('research_busy','Another research project is already active.');$db->begin_transaction();try{$state=$db->query("SELECT points FROM research_state WHERE userid=$uid FOR UPDATE")->fetch_assoc();if((float)$state['points']<(int)$t['rp_cost'])throw new RuntimeException('points');$due=time()+(int)$t['duration'];$db->query("UPDATE research_state SET points=points-".(int)$t['rp_cost']." WHERE userid=$uid");$db->query("INSERT INTO research_jobs(userid,tech_id,due) VALUES($uid,$tech,$due)");$db->commit();}catch(RuntimeException$e){$db->rollback();json_err('research_points','Not enough research points.');}catch(Throwable$e){$db->rollback();throw$e;}json_out(['ok'=>true,'message'=>$t['name'].' research started.','due'=>$due]);
}
$state=$db->query("SELECT points,last_tick FROM research_state WHERE userid=$uid LIMIT 1")->fetch_assoc();$workers=0;if($center>0){$w=$db->query("SELECT COUNT(*) n FROM survivors WHERE userid=$uid AND job_facility=12 AND hp>0 AND fatigue<90");$workers=$w?(int)$w->fetch_assoc()['n']:0;}$rate=$center>0?2+$center*2+$workers*12:0;
$job=null;$jq=$db->query("SELECT j.tech_id,j.due,t.name FROM research_jobs j JOIN technologies t ON t.id=j.tech_id WHERE j.userid=$uid LIMIT 1");if($jq&&$jq->num_rows){$j=$jq->fetch_assoc();$job=['techId'=>(int)$j['tech_id'],'name'=>$j['name'],'due'=>(int)$j['due']];}
$done=[];$dr=$db->query("SELECT tech_id FROM player_research WHERE userid=$uid");while($dr&&($d=$dr->fetch_assoc()))$done[(int)$d['tech_id']]=true;
$branches=[];$r=$db->query("SELECT * FROM technologies ORDER BY branch,tier");while($r&&($t=$r->fetch_assoc())){$id=(int)$t['id'];$complete=isset($done[$id]);$prereq=(int)($t['prereq_id']??0);$reason='';if($center<=0)$reason='Research center required';elseif($center<(int)$t['center_level'])$reason='Center level '.(int)$t['center_level'].' required';elseif($prereq&&!isset($done[$prereq]))$reason='Previous technology required';elseif($job)$reason='Research already active';elseif((float)$state['points']<(int)$t['rp_cost'])$reason='Need '.(int)$t['rp_cost'].' RP';$node=['id'=>$id,'tier'=>(int)$t['tier'],'name'=>$t['name'],'description'=>$t['description'],'cost'=>(int)$t['rp_cost'],'duration'=>(int)$t['duration'],'centerLevel'=>(int)$t['center_level'],'prereq'=>$prereq?:null,'complete'=>$complete,'active'=>$job&&$job['techId']===$id,'canResearch'=>!$complete&&!$reason,'reason'=>$complete?'Recovered':$reason];$branches[$t['branch']][]=$node;}
json_out(['ok'=>true,'centerLevel'=>$center,'points'=>round((float)$state['points'],1),'rate'=>$rate,'workers'=>$workers,'job'=>$job,'branches'=>$branches]);
