<?php
require __DIR__ . '/_bootstrap.php';global $db;$uid=api_require_user();zv2_refresh($uid);
$sh=$db->query("SELECT buildings FROM strongholds WHERE userid=$uid LIMIT 1")->fetch_assoc();$buildings=pipe_nums($sh['buildings']);$center=(int)($buildings[12]??0);zv2_refresh_research($uid,$buildings);
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'&&($_POST['action']??'')==='cancel'){
 // OG cancelresearch: abort the project, refund HALF the research points.
 $jq=$db->query("SELECT j.tech_id,t.rp_cost,t.name FROM research_jobs j JOIN technologies t ON t.id=j.tech_id WHERE j.userid=$uid LIMIT 1");
 if(!$jq||!$jq->num_rows)json_err('no_research','No research project to cancel.');$j=$jq->fetch_assoc();$refund=(int)floor((int)$j['rp_cost']/2);
 $db->begin_transaction();try{$db->query("DELETE FROM research_jobs WHERE userid=$uid");$db->query("UPDATE research_state SET points=points+$refund WHERE userid=$uid");$db->commit();}catch(Throwable$e){$db->rollback();throw$e;}
 json_out(['ok'=>true,'message'=>$j['name'].' canceled — '.$refund.' RP recovered.']);
}
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
 $tech=(int)($_POST['tech']??0);$tq=$db->query("SELECT * FROM technologies WHERE id=$tech LIMIT 1");if(!$tq||!$tq->num_rows)json_err('bad_tech','Unknown technology.');$t=$tq->fetch_assoc();if($center<=0&&(int)$t['center_level']>0)json_err('no_center','Construct a Research center first.');if($center<(int)$t['center_level'])json_err('center_level','Research center level '.(int)$t['center_level'].' required.');$reqFac=(int)($t['req_facility']??0);$reqLvl=(int)($t['req_level']??0);if($reqFac&&(int)($buildings[$reqFac]??0)<$reqLvl){$fn=$db->query("SELECT name FROM facilities WHERE id=$reqFac LIMIT 1");$fname=$fn&&$fn->num_rows?$fn->fetch_assoc()['name']:('Facility '.$reqFac);json_err('facility_level',$fname.' level '.$reqLvl.' required.');}if(zv2_has_tech($uid,$tech))json_err('completed','That technology is already recovered.');if((int)$t['prereq_id']&&!zv2_has_tech($uid,(int)$t['prereq_id']))json_err('prerequisite','Recover the previous technology in this branch first.');$busy=$db->query("SELECT 1 FROM research_jobs WHERE userid=$uid LIMIT 1");if($busy&&$busy->num_rows)json_err('research_busy','Another research project is already active.');$db->begin_transaction();try{$state=$db->query("SELECT points FROM research_state WHERE userid=$uid FOR UPDATE")->fetch_assoc();if((float)$state['points']<(int)$t['rp_cost'])throw new RuntimeException('points');$due=time()+(int)$t['duration'];$db->query("UPDATE research_state SET points=points-".(int)$t['rp_cost']." WHERE userid=$uid");$db->query("INSERT INTO research_jobs(userid,tech_id,due) VALUES($uid,$tech,$due)");$db->commit();}catch(RuntimeException$e){$db->rollback();json_err('research_points','Not enough research points.');}catch(Throwable$e){$db->rollback();throw$e;}json_out(['ok'=>true,'message'=>$t['name'].' research started.','due'=>$due]);
}
$state=$db->query("SELECT points,last_tick FROM research_state WHERE userid=$uid LIMIT 1")->fetch_assoc();$workers=0;if($center>0){$w=$db->query("SELECT COUNT(*) n FROM survivors WHERE userid=$uid AND job_facility=12 AND hp>0 AND fatigue<90");$workers=$w?(int)$w->fetch_assoc()['n']:0;}$rate=$center>0?2+$center*2+$workers*12:0;
$job=null;$jq=$db->query("SELECT j.tech_id,j.due,t.name FROM research_jobs j JOIN technologies t ON t.id=j.tech_id WHERE j.userid=$uid LIMIT 1");if($jq&&$jq->num_rows){$j=$jq->fetch_assoc();$job=['techId'=>(int)$j['tech_id'],'name'=>$j['name'],'due'=>(int)$j['due']];}
$done=[];$dr=$db->query("SELECT tech_id FROM player_research WHERE userid=$uid");while($dr&&($d=$dr->fetch_assoc()))$done[(int)$d['tech_id']]=true;
$facNames=[];$fq=$db->query("SELECT id,name FROM facilities");while($fq&&($f=$fq->fetch_assoc()))$facNames[(int)$f['id']]=$f['name'];
$benefitLabels=['build_speed'=>'Faster compound construction','salvage_bonus'=>'More materials recovered from rooms','durability_bonus'=>'Higher durability on newly acquired equipment','defense_bonus'=>'More compound defence against raids','room_loot'=>'More loot recovered from every room','intel_bonus'=>'More intelligence when discovering rooms','water_rate'=>'Higher water production','food_rate'=>'Higher food production','healing_bonus'=>'More health restored by healing items','recovery_rate'=>'Faster Hospital recovery','power_bonus'=>'Higher power production','petrol_rate'=>'Higher petrol production','leadership'=>'More squad carrying capacity','combat_bonus'=>'Higher attack in room combat','travel_speed'=>'Faster squad travel'];
$unlockLabels=['unlock_repair'=>'Unlocks repair-kit and crowbar recipes','unlock_machete'=>'Unlocks the machete recipe','unlock_pistol'=>'Unlocks improvised firearm recipes','unlock_ammo'=>'Unlocks ammunition and service-pistol recipes'];
$branches=[];$r=$db->query("SELECT * FROM technologies ORDER BY branch,tier");while($r&&($t=$r->fetch_assoc())){$id=(int)$t['id'];$complete=isset($done[$id]);$prereq=(int)($t['prereq_id']??0);$reqFac=(int)($t['req_facility']??0);$reqLvl=(int)($t['req_level']??0);$facName=$reqFac?($facNames[$reqFac]??('Facility '.$reqFac)):null;$effect=$t['effect_key'];$value=(float)$t['effect_value'];$amount=rtrim(rtrim(number_format($value,2,'.',''),'0'),'.');$flat=in_array($effect,['healing_bonus','combat_bonus','intel_bonus','defense_bonus'],true);$benefit=$unlockLabels[$effect]??('+'.$amount.($flat?' ':'% ').($benefitLabels[$effect]??str_replace('_',' ',$effect)));$reason='';if($center<=0&&(int)$t['center_level']>0)$reason='Research center required';elseif($center<(int)$t['center_level'])$reason='Center level '.(int)$t['center_level'].' required';elseif($reqFac&&(int)($buildings[$reqFac]??0)<$reqLvl)$reason=$facName.' L'.$reqLvl.' required';elseif($prereq&&!isset($done[$prereq]))$reason='Previous technology required';elseif($job)$reason='Research already active';elseif((float)$state['points']<(int)$t['rp_cost'])$reason='Need '.(int)$t['rp_cost'].' RP';$node=['id'=>$id,'tier'=>(int)$t['tier'],'name'=>$t['name'],'description'=>$t['description'],'benefit'=>$benefit,'cost'=>(int)$t['rp_cost'],'duration'=>(int)$t['duration'],'centerLevel'=>(int)$t['center_level'],'reqFacility'=>$reqFac?:null,'reqFacilityName'=>$facName,'reqLevel'=>$reqLvl,'prereq'=>$prereq?:null,'complete'=>$complete,'active'=>$job&&$job['techId']===$id,'canResearch'=>!$complete&&!$reason,'reason'=>$complete?'Recovered':$reason];$branches[$t['branch']][]=$node;}
json_out(['ok'=>true,'centerLevel'=>$center,'points'=>round((float)$state['points'],1),'rate'=>$rate,'workers'=>$workers,'job'=>$job,'branches'=>$branches]);
