<?php
require __DIR__ . '/_bootstrap.php';global $db;$uid=api_require_user();if(($_SERVER['REQUEST_METHOD']??'GET')!=='POST')json_err('method','POST required',405);
$x=(int)($_POST['x']??0);$y=(int)($_POST['y']??0);$roomId=(int)($_POST['room']??0);$action=(string)($_POST['action']??'');$squadId=(int)($_POST['squad']??0);if($x<1||$x>50||$y<1||$y>50||$roomId<=0)json_err('bad_room','Invalid room.');if(!zv2_is_seen($uid,$x,$y))json_err('not_discovered','Explore this place first.',403);$activeSquad=zv2_squad($uid,$squadId);if($activeSquad['traveling']||$activeSquad['x']!==$x||$activeSquad['y']!==$y)json_err('squad_elsewhere','The selected squad must be at this building.');if(!$activeSquad['crew'])json_err('no_crew','This squad has no members.');$crewSql=implode(',',array_map('intval',$activeSquad['crew']));$gearAttack=(int)$activeSquad['equipment']['perMemberAttack'];$gearDefense=(int)$activeSquad['equipment']['perMemberDefense'];
$rr=$db->query("SELECT r.id,r.buildingid,r.inventory,r.zombies FROM roommap r JOIN buildings b ON b.id=r.buildingid WHERE r.id=$roomId AND b.x=$x AND b.y=$y LIMIT 1");if(!$rr||!$rr->num_rows)json_err('no_room','That room does not belong to this location.',404);$room=$rr->fetch_assoc();$bid=(int)$room['buildingid'];$techEffects=zv2_tech_effects($uid);$db->query("INSERT IGNORE INTO building_runs(userid,building_id) VALUES($uid,$bid)");
function groups(string $encoded):array{$out=[];foreach(explode('&',$encoded)as$e){if($e==='')continue;$b=explode('|',$e);$t=(int)($b[0]??0);$n=max(0,(int)($b[1]??0));if($t&&$n)$out[]=['type'=>$t,'count'=>$n];}return$out;}
function threat(array $groups):array{global $db;$n=0;$t=0;foreach($groups as$g){if($g['count']<=0)continue;$n+=$g['count'];$r=$db->query("SELECT threat FROM zombietypes WHERE id=".(int)$g['type']." LIMIT 1");$v=$r&&$r->num_rows?(int)$r->fetch_assoc()['threat']:1;$t+=$g['count']*$v;}return[$n,$t];}
function add_room_item(string $encoded,int $item,int $amount):string{$entries=[];$found=false;foreach(explode('&',$encoded)as$e){if($e==='')continue;$b=explode('|',$e);$id=(int)($b[0]??0);$n=(int)($b[1]??0);if($id===$item){$n+=$amount;$found=true;}$entries[]=$id.'|'.$n;}if(!$found)$entries[]=$item.'|'.$amount;return implode('&',$entries);}
function momentum(int $uid,int $bid,int $gain):array{global $db;$r=$db->query("SELECT momentum,reward_tier FROM building_runs WHERE userid=$uid AND building_id=$bid FOR UPDATE");$run=$r->fetch_assoc();$value=min(15,(int)$run['momentum']+$gain);$tier=(int)floor($value/5);$old=(int)$run['reward_tier'];$reward=null;if($tier>$old){$item=[1,5,6][($bid+$tier)%3];$amount=$item===6?4:1;zv2_add_item($uid,$item,$amount);$reward=['name'=>zv2_item_name($item),'amount'=>$amount,'tier'=>$tier];}$db->query("UPDATE building_runs SET momentum=$value,reward_tier=GREATEST(reward_tier,$tier) WHERE userid=$uid AND building_id=$bid");return['value'=>$value,'nextReward'=>($tier+1)*5,'reward'=>$reward];}
function noise(int $uid,int $bid,int $gain):int{global $db;$db->query("UPDATE building_runs SET noise=LEAST(12,noise+$gain) WHERE userid=$uid AND building_id=$bid");return(int)$db->query("SELECT noise FROM building_runs WHERE userid=$uid AND building_id=$bid")->fetch_assoc()['noise'];}

if($action==='discover'){
 $known=$db->query("SELECT discovered FROM room_progress WHERE userid=$uid AND room_id=$roomId LIMIT 1");if($known&&$known->num_rows&&(int)$known->fetch_assoc()['discovered'])json_err('already_discovered','This room is already mapped.');
 $prev=$db->query("SELECT r.id,r.zombies,COALESCE(p.discovered,0) discovered FROM roommap r LEFT JOIN room_progress p ON p.room_id=r.id AND p.userid=$uid WHERE r.buildingid=$bid AND r.id<$roomId ORDER BY r.id DESC LIMIT 1");if($prev&&$prev->num_rows){$p=$prev->fetch_assoc();if(!(int)$p['discovered']||(string)$p['zombies']!=='')json_err('route_blocked','Secure the previous room first.');}
 $approach=(string)($_POST['approach']??'quiet');if(!in_array($approach,['quiet','careful','breach'],true))json_err('bad_approach','Choose an entry approach.');$intel=($approach==='careful'?3:($approach==='quiet'?2:0))+(int)($techEffects['intel_bonus']??0);if($approach==='careful'&&zv2_item_owned($uid,26)>0)$intel++;$gain=$approach==='breach'?2:1;$event='';
 if($approach==='careful'){$bonus=[1,2,5,6][($roomId+$uid)%4];$newInv=add_room_item((string)$room['inventory'],$bonus,1);$esc=$db->real_escape_string($newInv);$db->query("UPDATE roommap SET inventory='$esc' WHERE id=$roomId");$event='Careful scouting uncovered bonus salvage.';}
 if($approach==='breach'){$sv=$db->query("SELECT id,name FROM survivors WHERE userid=$uid AND id IN ($crewSql) AND hp>0 AND fatigue<90 AND job_facility IS NULL ORDER BY fatigue,id LIMIT 1");if(!$sv||!$sv->num_rows)json_err('no_breacher','No survivor in this squad is available to breach.');$s=$sv->fetch_assoc();$ambush=(string)$room['zombies']!==''?1:0;$db->query("UPDATE survivors SET hp=GREATEST(0,hp-$ambush),fatigue=LEAST(100,fatigue+10) WHERE id=".(int)$s['id']);$event=$ambush?$s['name'].' took 1 ambush damage.':$s['name'].' smashed through uncontested.';}
 $approachEsc=$db->real_escape_string($approach);$db->query("INSERT INTO room_progress(userid,room_id,discovered,intel,approach,discovered_at) VALUES($uid,$roomId,1,$intel,'$approachEsc',".time().") ON DUPLICATE KEY UPDATE discovered=1,intel=$intel,approach='$approachEsc',discovered_at=VALUES(discovered_at)");$m=momentum($uid,$bid,$gain);$n=noise($uid,$bid,$approach==='breach'?4:($approach==='careful'?1:0));json_out(['ok'=>true,'action'=>'discover','approach'=>$approach,'intel'=>$intel,'momentum'=>$m,'noise'=>$n,'message'=>ucfirst($approach).' entry complete. '.$event.($n>=6?' The building is dangerously loud.':'')]);
}

$pr=$db->query("SELECT intel FROM room_progress WHERE userid=$uid AND room_id=$roomId AND discovered=1 LIMIT 1");if(!$pr||!$pr->num_rows)json_err('room_unknown','Discover this room before acting inside it.');$progress=$pr->fetch_assoc();
if($action==='retreat'){[$remaining]=threat(groups((string)$room['zombies']));if($remaining<=0)json_err('already_clear','There is nothing to retreat from.');json_out(['ok'=>true,'action'=>'retreat','remaining'=>$remaining,'retreated'=>true,'message'=>'The squad disengaged. Momentum is safe, but the room remains infected.']);}
if($action==='fight'){
 $survivorId=(int)($_POST['survivor']??0);if(!in_array($survivorId,$activeSquad['crew'],true))json_err('not_in_squad','Choose a fighter from the selected squad.');$tactic=(string)($_POST['tactic']??'precise');if(!in_array($tactic,['precise','aggressive','guarded'],true))$tactic='precise';$sr=$db->query("SELECT s.id,s.name,s.hp,s.max_hp,s.attack_stat,s.defense_stat,s.equipped_weapon,s.job_facility,s.fatigue,i.name weapon,i.attack_bonus,i.ammo_item,i.max_durability,COALESCE(v.durability,i.max_durability) durability,COALESCE(a.amount,0) ammo FROM survivors s LEFT JOIN items i ON i.id=s.equipped_weapon LEFT JOIN inventory v ON v.userid=s.userid AND v.item_id=s.equipped_weapon LEFT JOIN inventory a ON a.userid=s.userid AND a.item_id=i.ammo_item WHERE s.id=$survivorId AND s.userid=$uid LIMIT 1");if(!$sr||!$sr->num_rows)json_err('bad_survivor','Choose one of your survivors.');$sv=$sr->fetch_assoc();if((int)$sv['hp']<=0)json_err('survivor_down',$sv['name'].' is unable to fight.');if($sv['job_facility']!==null)json_err('survivor_working',$sv['name'].' must leave facility duty first.');if((float)$sv['fatigue']>=90)json_err('survivor_exhausted',$sv['name'].' is too exhausted to fight.');
 $z=groups((string)$room['zombies']);[$total]=threat($z);if(!$total)json_err('already_clear','This room is already clear.');$condition=(int)($sv['durability']??0);$needsAmmo=(int)($sv['ammo_item']??0)>0;$weaponUsed=(int)($sv['equipped_weapon']??0)>0&&$condition>0&&(!$needsAmmo||(int)$sv['ammo']>0);$intel=min(4,(int)$progress['intel']);$attack=(int)$sv['attack_stat']+($weaponUsed?(int)$sv['attack_bonus']:0)+$gearAttack+$intel+(int)($techEffects['combat_bonus']??0)+($tactic==='aggressive'?3:($tactic==='guarded'?-1:0));$budget=max(1,(int)floor($attack/3));$killed=0;foreach($z as&$g){$take=min($g['count'],$budget);$g['count']-=$take;$budget-=$take;$killed+=$take;if(!$budget)break;}unset($g);[$remaining,$danger]=threat($z);$currentNoise=(int)$db->query("SELECT noise FROM building_runs WHERE userid=$uid AND building_id=$bid")->fetch_assoc()['noise'];$damage=$remaining?max(1,(int)ceil($danger/3)-((int)$sv['defense_stat']+$gearDefense)+(int)floor($currentNoise/5)):0;if($tactic==='guarded')$damage=max(0,$damage-2);if($tactic==='aggressive'&&$remaining)$damage++;$fatigue=$tactic==='aggressive'?12:($tactic==='guarded'?5:8);$newHp=max(0,(int)$sv['hp']-$damage);$alive=array_values(array_filter($z,fn($g)=>$g['count']>0));$encoded=implode('&',array_map(fn($g)=>$g['type'].'|'.$g['count'],$alive));$ze=$db->real_escape_string($encoded);$newCondition=$weaponUsed?max(0,$condition-1):$condition;$newAmmo=$needsAmmo&&$weaponUsed?max(0,(int)$sv['ammo']-1):(int)$sv['ammo'];$m=null;
 $db->begin_transaction();try{$db->query("UPDATE roommap SET zombies='$ze' WHERE id=$roomId");$db->query("UPDATE survivors SET hp=$newHp,fatigue=LEAST(100,fatigue+$fatigue) WHERE id=$survivorId AND userid=$uid");$db->query("UPDATE room_progress SET intel=GREATEST(0,intel-1) WHERE userid=$uid AND room_id=$roomId");if($weaponUsed){$wid=(int)$sv['equipped_weapon'];$db->query("UPDATE inventory SET durability=$newCondition WHERE userid=$uid AND item_id=$wid");if($needsAmmo){$aid=(int)$sv['ammo_item'];$db->query("UPDATE inventory SET amount=amount-1 WHERE userid=$uid AND item_id=$aid AND amount>0");$db->query("DELETE FROM inventory WHERE userid=$uid AND item_id=$aid AND amount<=0");}}if($remaining===0)$m=momentum($uid,$bid,$tactic==='aggressive'?3:($tactic==='guarded'?1:2));$db->commit();}catch(Throwable$e){$db->rollback();throw$e;}
 $n=noise($uid,$bid,$tactic==='aggressive'?4:($tactic==='precise'?1:0));$message=ucfirst($tactic)." stance: $killed killed".($damage?", $damage damage taken":', no damage').'.';if($gearAttack||$gearDefense)$message.=" Squad gear: +$gearAttack ATK / +$gearDefense DEF per member.";if($remaining===0)$message.=' Room secured!';if($n>=6)$message.=' Noise is attracting nearby infected.';if($m&&$m['reward'])$message.=' Supply cache earned: '.$m['reward']['amount'].'× '.$m['reward']['name'].'.';json_out(['ok'=>true,'action'=>'fight','tactic'=>$tactic,'killed'=>$killed,'remaining'=>$remaining,'secured'=>$remaining===0,'noise'=>$n,'squadGear'=>['attack'=>$gearAttack,'defense'=>$gearDefense],'survivor'=>['id'=>$survivorId,'name'=>$sv['name'],'hp'=>$newHp,'maxHp'=>(int)$sv['max_hp'],'damage'=>$damage,'fatigue'=>$fatigue],'weapon'=>['used'=>$weaponUsed,'name'=>$sv['weapon'],'durability'=>$newCondition,'maxDurability'=>(int)($sv['max_durability']??0),'ammo'=>$newAmmo],'momentum'=>$m,'message'=>$message]);
}
if($action==='loot'){
 if((string)$room['zombies']!=='')json_err('room_infected','Clear the zombies before scavenging.');$itemId=(int)($_POST['item']??0);$available=0;foreach(explode('&',(string)$room['inventory'])as$e){$b=explode('|',$e);if((int)($b[0]??0)===$itemId)$available=max(0,(int)($b[1]??0));}if(!$available)json_err('item_gone','That item is no longer here.');
 $bonus=in_array($itemId,[1,2],true)&&($techEffects['salvage_bonus']??0)>0?max(1,(int)floor($available*$techEffects['salvage_bonus']/100)):0;$taken=zv2_add_cargo($activeSquad['id'],$itemId,$available+$bonus);if($taken<=0)json_err('cargo_full','The squad cannot carry any more. Return to the stronghold or leave something behind.');$actual=min($available,$taken);$remaining=$available-$actual;$left=[];foreach(explode('&',(string)$room['inventory'])as$e){if($e==='')continue;$b=explode('|',$e);if((int)($b[0]??0)===$itemId){if($remaining>0)$left[]=$itemId.'|'.$remaining;}else$left[]=$e;}$esc=$db->real_escape_string(implode('&',$left));$db->query("UPDATE roommap SET inventory='$esc' WHERE id=$roomId");if($itemId===8)$db->query("UPDATE research_state SET points=LEAST(9999,points+".($actual*5).") WHERE userid=$uid");$cargo=zv2_squad_cargo($activeSquad['id']);$message='Packed '.$taken.'× '.zv2_item_name($itemId).' into squad cargo.';if($taken<$available+$bonus)$message.=' Capacity reached; some supplies remain.';if($itemId===8)$message.=' Electronics yielded '.($actual*5).' research points.';$me=$db->real_escape_string($message);$db->query("INSERT INTO squad_events(squad_id,event_type,message,created_at) VALUES(".(int)$activeSquad['id'].",'loot','$me',".time().")");json_out(['ok'=>true,'action'=>'loot','item'=>['id'=>$itemId,'name'=>zv2_item_name($itemId),'amount'=>$taken,'remaining'=>$remaining],'cargo'=>$cargo,'message'=>$message]);
}
json_err('bad_action','Unknown room action.');
