<?php
require __DIR__ . '/_bootstrap.php';global $db;$uid=api_require_user();zv2_refresh($uid);

function tutorial_steps():array{return[
 ['title'=>'Welcome to the stronghold','body'=>'Your Headquarters is the command center. The resource bar shows supplies and hourly gathering. New settlements receive a temporary gathering boost while they get established.','objective'=>'Review the compound, then continue.','target'=>'hud'],
 ['title'=>'Protect what we find','body'=>'The original Z training began with Storage, and that still makes sense: returning squads need it to deposit loot and issue squad equipment. Click an empty compound plot and choose Storage.','objective'=>'Construct Storage level 1.','target'=>'compound'],
 ['title'=>'Secure water and food','body'=>'Life Support makes water and food gathering more productive. Every level now gives a permanent production bonus, and assigned survivors improve it further.','objective'=>'Construct Life Support level 1.','target'=>'compound'],
 ['title'=>'Turn ruins into materials','body'=>'The Scrapyard recovers timber and metal needed by nearly every other facility. Its levels and workers both raise material output.','objective'=>'Construct Scrapyard level 1.','target'=>'compound'],
 ['title'=>'Keep the lights on','body'=>'Facilities need reliable electricity. A Power Generator also lets assigned engineers add more power to the compound.','objective'=>'Construct Power Generator level 1.','target'=>'compound'],
 ['title'=>'Put survivors to work','body'=>'Open Life Support or the Scrapyard and assign one reserve survivor. Workers gather faster, but they leave the raiding crew until returned to reserve.','objective'=>'Assign a survivor to Life Support or the Scrapyard.','target'=>'compound'],
 ['title'=>'Recover lost knowledge','body'=>'The Research center rebuilds the old world\'s knowledge across eleven branches — from Materials to Defense. Each branch is gated by one of your facilities and the center itself. Recover your first technology.','objective'=>'Construct a Research center and complete one research project.','target'=>'research'],
 ['title'=>'Arm the settlement','body'=>'The Toolshop turns salvage into weapons, tools, medicine and compound defenses. Toolshop crew also speed up all construction. Craft anything — a wooden club is a fine start.','objective'=>'Construct the Toolshop and craft one item.','target'=>'toolshop'],
 ['title'=>'Look beyond the walls','body'=>'The city is explored by named squads. Open the world map; your active squad starts at the stronghold and can travel to an adjacent frontier block.','objective'=>'Open the world map.','target'=>'world'],
 ['title'=>'Explore the first block','body'=>'Choose a dashed frontier tile next to known ground. Travel takes time, and the squad marker shows progress along the route.','objective'=>'Reveal at least one new city block.','target'=>'world'],
 ['title'=>'Clear rooms and take supplies','body'=>'Enter the discovered building, choose how to open rooms, eliminate the infected, and pack an item into squad cargo. Quiet approaches create less danger.','objective'=>'Carry at least one looted item in squad cargo.','target'=>'world'],
 ['title'=>'Bring the loot home','body'=>'Use Return Home in the Squads window. Once the squad arrives, deposit its cargo into Storage so the items become available for crafting and equipment.','objective'=>'Return and deposit squad loot in Storage.','target'=>'squads'],
 ['title'=>'Put wheels under the squad','body'=>'Build a Garage, then open Squads. Restore a Trail Motorcycle or larger vehicle and assign it to a squad at home. Vehicles consume fuel but shorten travel and add passenger and cargo capacity; Garage upgrades unlock larger vehicles and vehicle upgrades.','objective'=>'Assign a restored vehicle to any squad.','target'=>'squads'],
 ['title'=>'The stronghold is yours','body'=>'You now know the core loop: build, staff, explore, fight, loot, return, and improve. Research, the Toolshop, new recruits, and stronger defenses are your next priorities.','objective'=>'Tutorial complete.','target'=>'none'],
];}
function tutorial_ready(int $uid,int $step):bool{global $db;if($step===0||$step>=13)return true;$h=$db->query("SELECT buildings FROM strongholds WHERE userid=$uid LIMIT 1")->fetch_assoc();$levels=pipe_nums($h['buildings']);if($step===1)return(int)($levels[4]??0)>0;if($step===2)return(int)($levels[1]??0)>0;if($step===3)return(int)($levels[2]??0)>0;if($step===4)return(int)($levels[9]??0)>0;if($step===5){$r=$db->query("SELECT 1 FROM survivors WHERE userid=$uid AND job_facility IN(1,2) LIMIT 1");return$r&&$r->num_rows>0;}
 if($step===6){$r=$db->query("SELECT 1 FROM player_research WHERE userid=$uid LIMIT 1");return$r&&$r->num_rows>0;}
 if($step===7){if((int)($levels[11]??0)<1)return false;$r=$db->query("SELECT 1 FROM inventory WHERE userid=$uid AND item_id IN (9,10,11,12,13,14,15,16,17,19,20,21,22,23,24,25,26) AND amount>0 LIMIT 1");if($r&&$r->num_rows)return true;$j=$db->query("SELECT 1 FROM production_jobs WHERE userid=$uid LIMIT 1");return$j&&$j->num_rows>0;}
 if($step===8)return false;if($step===9){$r=$db->query("SELECT data FROM discovered WHERE userid=$uid LIMIT 1");return$r&&$r->num_rows&&substr_count($r->fetch_assoc()['data'],'1')>1;}if($step===10){$r=$db->query("SELECT 1 FROM squad_events e JOIN squads q ON q.id=e.squad_id JOIN squad_cargo c ON c.squad_id=q.id WHERE q.userid=$uid AND e.event_type='loot' AND c.amount>0 LIMIT 1");return$r&&$r->num_rows>0;}if($step===11){$r=$db->query("SELECT 1 FROM squad_events e JOIN squads q ON q.id=e.squad_id WHERE q.userid=$uid AND e.event_type='deposit' LIMIT 1");return$r&&$r->num_rows>0;}if($step===12){$r=$db->query("SELECT 1 FROM vehicles WHERE userid=$uid AND assigned_squad IS NOT NULL LIMIT 1");return$r&&$r->num_rows>0;}return false;}
function tutorial_payload(int $uid):array{global $db;$r=$db->query("SELECT step,dismissed,updated_at FROM tutorial_progress WHERE userid=$uid LIMIT 1");$steps=tutorial_steps();if(!$r||!$r->num_rows)return['ok'=>true,'available'=>true,'active'=>false,'complete'=>false,'dismissed'=>false,'step'=>0,'total'=>count($steps)-1,'ready'=>true,'content'=>$steps[0]];$p=$r->fetch_assoc();$step=min(count($steps)-1,max(0,(int)$p['step']));$complete=$step>=count($steps)-1;return['ok'=>true,'available'=>true,'active'=>(int)$p['dismissed']===0&&!$complete,'complete'=>$complete,'dismissed'=>(bool)$p['dismissed'],'step'=>$step,'total'=>count($steps)-1,'ready'=>tutorial_ready($uid,$step),'content'=>$steps[$step]];}

if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){$action=(string)($_POST['action']??'');$now=time();if($action==='restart'){$db->query("INSERT INTO tutorial_progress(userid,step,dismissed,updated_at) VALUES($uid,0,0,$now) ON DUPLICATE KEY UPDATE step=0,dismissed=0,updated_at=$now");json_out(tutorial_payload($uid));}if($action==='dismiss'){$db->query("UPDATE tutorial_progress SET dismissed=1,updated_at=$now WHERE userid=$uid");json_out(tutorial_payload($uid));}if(!in_array($action,['advance','event'],true))json_err('bad_action','Unknown tutorial action.');$r=$db->query("SELECT step,dismissed FROM tutorial_progress WHERE userid=$uid LIMIT 1");if(!$r||!$r->num_rows)json_err('tutorial_inactive','Start the tutorial first.');$p=$r->fetch_assoc();$step=(int)$p['step'];if((int)$p['dismissed'])json_err('tutorial_dismissed','Restart the tutorial to continue.');$event=(string)($_POST['event']??'');$ready=$step===8&&$action==='event'&&$event==='world'?true:($action==='advance'&&$step!==8&&tutorial_ready($uid,$step));if(!$ready)json_err('objective_incomplete','Complete the current objective first.');$next=min(count(tutorial_steps())-1,$step+1);$db->query("UPDATE tutorial_progress SET step=$next,updated_at=$now WHERE userid=$uid");json_out(tutorial_payload($uid));}
json_out(tutorial_payload($uid));
